export const VERSION='1.0.0';
export const WORLDS=[
 {id:'bones',name:'Ogrody Osteonu',domain:'Anatomia',boss:'Cervus, Strażnik Kości',sprite:4,color:'#71d7bb',floor:1,props:[4,8,10],shape:'cloister',rule:'Pancerz: technika przebija osłonę Strażnika.',story:'Atlas stracił pamięć o ruchu. W ogrodach kości czeka pierwszy fragment.',ending:'Kości pamiętają już swoje imiona. Pierwsza pieczęć Atlasu rozbłyska.',pattern:['strike','guard','heavy']},
 {id:'muscle',name:'Kuźnia Włókien',domain:'Biomechanika',boss:'Myo, Serce Kuźni',sprite:5,color:'#f58f68',floor:2,props:[5,13,15],shape:'lanes',rule:'Narastające napięcie: silny atak co trzecią turę.',story:'Ogień Kuźni zgasł w bezruchu. Przywróć rytm włóknom.',ending:'Kuźnia znów oddycha ruchem. Siła bez kontroli ustępuje koordynacji.',pattern:['strike','charge','heavy']},
 {id:'neuro',name:'Sieć Synaps',domain:'Układ nerwowy',boss:'Synapta, Iskra Pamięci',sprite:6,color:'#6ddce8',floor:2,props:[6,7,9],shape:'branch',rule:'Zakłócenie zabiera skupienie. Osłona chroni przed nim.',story:'W rozgałęzieniach Sieci zaginął impuls. Podążaj za światłem.',ending:'Sygnał dociera do celu. Rozproszone ścieżki łączą się w Sieć.',pattern:['drain','strike','heavy']},
 {id:'breath',name:'Przypływ Oddechu',domain:'Fizjologia',boss:'Pneuma, Sowa Przypływu',sprite:7,color:'#87bfff',floor:1,props:[7,11,12],shape:'islands',rule:'Odpływ: co trzecią turę wróg odzyskuje zdrowie.',story:'Wyspy unoszą się w rytmie cichego oddechu. Posłuchaj ich.',ending:'Wdech spotyka wydech. Przypływ znów ma swój rytm.',pattern:['strike','heavy','heal']},
 {id:'mind',name:'Lustrzane Archiwum',domain:'Psychologia',boss:'Mnema, Ćma Wspomnień',sprite:8,color:'#c8a2ff',floor:2,props:[6,9,10],shape:'mirror',rule:'Odbicie: osłona wroga osłabia zwykły atak.',story:'Archiwum nie pyta, ile przeczytałeś. Pyta, co potrafisz przywołać.',ending:'Lustra przestają mylić. Wspomnienia znajdują swoje miejsca.',pattern:['guard','drain','heavy']},
 {id:'nature',name:'Zielone Źródło',domain:'Natura',boss:'Verdan, Ogród na Grzbiecie',sprite:9,color:'#a7d379',floor:0,props:[4,7,11],shape:'grove',rule:'Regeneracja: przerwij leczenie trafną analizą.',story:'Las zarósł zapomnianą ścieżkę. Odkryj, co łączy wszystkie żywe istoty.',ending:'Źródło znów płynie. Ogród otwiera drogę następnym wędrowcom.',pattern:['heal','guard','strike']},
 {id:'physics',name:'Obserwatorium Sił',domain:'Fizyka',boss:'Graviton, Mechaniczny Strażnik',sprite:10,color:'#ebc87a',floor:2,props:[6,8,15],shape:'ring',rule:'Bezwładność: po ładowaniu nadchodzi ciężki atak.',story:'Kręgi Obserwatorium zastygły. Rozpoznaj siły, które wprawiają je w ruch.',ending:'Pierścienie ruszają. Atlas znów rozumie siłę, energię i równowagę.',pattern:['charge','heavy','drain']},
 {id:'care',name:'Latarnia Powrotu',domain:'Praktyka fizjo',boss:'Aureon, Ostatnie Echo',sprite:11,color:'#ffc17b',floor:1,props:[8,10,14],shape:'star',rule:'Trzy fazy: ostatni Strażnik zmienia sekwencję po utracie zdrowia.',story:'Osiem dróg spotyka się w Latarni. Ostatni fragment czeka na uważność.',ending:'Atlas jest cały. Wiedza ożyła w decyzjach, a ruch wrócił do krain. Możesz wrócić po sekrety lub podjąć wyższe wyzwanie.',pattern:['strike','guard','drain','charge','heavy']}
];
export const CLASSES=[
 {id:'guardian',name:'Strażnik',subtitle:'Spokój i wytrzymałość',desc:'110 zdrowia. Osłona odbija 6 obrażeń. Dobry początek przygody.',hp:110,power:16},
 {id:'seeker',name:'Odkrywca',subtitle:'Technika i tempo',desc:'95 zdrowia. Technika kosztuje o 1 skupienie mniej.',hp:95,power:18},
 {id:'scholar',name:'Uczony',subtitle:'Wiedza staje się siłą',desc:'90 zdrowia. Trafna analiza daje dodatkowe 8 obrażeń.',hp:90,power:17}
];
export const RELICS=[
 {id:'echo',name:'Echo kroku',desc:'Co trzeci zwykły atak uderza drugi raz.',symbol:'III',rarity:'RZADKI'},
 {id:'thorn',name:'Korona cierni',desc:'Każda osłona odbija dodatkowe 8 obrażeń.',symbol:'✦',rarity:'RZADKI'},
 {id:'flow',name:'Pierścień przepływu',desc:'Technika odzyskuje 1 skupienie po trafieniu.',symbol:'◎',rarity:'RZADKI'},
 {id:'lumen',name:'Latarnia poznania',desc:'Poprawna analiza przywraca 10 zdrowia.',symbol:'◇',rarity:'RZADKI'},
 {id:'roots',name:'Serce korzeni',desc:'Po zwycięstwie odzyskujesz 12 zdrowia.',symbol:'♧',rarity:'NIEPOSPOLITY'},
 {id:'edge',name:'Krawędź świtu',desc:'Gdy masz mniej niż połowę zdrowia, zadajesz +7 obrażeń.',symbol:'△',rarity:'RZADKI'},
 {id:'bastion',name:'Kościany bastion',desc:'Każdy otrzymany cios jest słabszy o 3.',symbol:'⬡',rarity:'NIEPOSPOLITY'},
 {id:'spark',name:'Iskra początku',desc:'Rozpoczynasz walkę z pełnym skupieniem i 12 osłony.',symbol:'ϟ',rarity:'NIEPOSPOLITY'},
 {id:'lens',name:'Soczewka prawdy',desc:'Poprawna analiza zadaje dodatkowe 9 obrażeń.',symbol:'◈',rarity:'RZADKI'},
 {id:'pulse',name:'Puls życia',desc:'Eliksir leczy o 15 zdrowia więcej.',symbol:'♡',rarity:'NIEPOSPOLITY'},
 {id:'gold',name:'Moneta wędrowca',desc:'Zwycięstwo daje dodatkowe 12 monet.',symbol:'¤',rarity:'NIEPOSPOLITY'},
 {id:'rhythm',name:'Rytm oddechu',desc:'Osłona przywraca 5 zdrowia.',symbol:'≈',rarity:'RZADKI'}
];
export const SOURCE_LINKS={
 anatomy:{title:'OpenStax: Anatomy and Physiology 2e',url:'https://openstax.org/books/anatomy-and-physiology-2e/pages/1-introduction'},
 memory:{title:'OpenStax: Psychology 2e — Memory',url:'https://openstax.org/books/psychology-2e/pages/8-4-ways-to-enhance-memory'},
 biology:{title:'OpenStax: Biology 2e',url:'https://openstax.org/books/biology-2e/pages/1-introduction'},
 physics:{title:'OpenStax: University Physics Volume 1',url:'https://openstax.org/books/university-physics-volume-1/pages/1-introduction'},
 nice:{title:'NICE NG59: Low back pain and sciatica',url:'https://www.nice.org.uk/guidance/ng59'},
 pain:{title:'IASP: Terminology — Pain',url:'https://www.iasp-pain.org/resources/terminology/'}
};
// Original short questions. PL / EN / Latin names are shown when they apply.
const rows=[
 ['bones','femur','Kość udowa','Femur','femur','Najdłuższa kość ciała to…','kość udowa','kość ramienna|kość łokciowa','Kość udowa tworzy szkielet uda i przenosi obciążenie między biodrem a kolanem.','anatomy'],
 ['bones','scapula','Łopatka','Scapula','scapula','Która kość ma wydrążenie stawowe dla głowy kości ramiennej?','łopatka','mostek|obojczyk','Wydrążenie stawowe łopatki współtworzy staw ramienny.','anatomy'],
 ['bones','patella','Rzepka','Patella','patella','Która kość jest trzeszczką w aparacie wyprostnym kolana?','rzepka','kość skokowa|kość łódkowata','Rzepka leży w ścięgnie mięśnia czworogłowego i zwiększa jego ramię działania.','anatomy'],
 ['bones','radius','Kość promieniowa','Radius','radius','Po której stronie przedramienia leży kość promieniowa w pozycji anatomicznej?','po stronie kciuka','po stronie małego palca|po stronie łokcia wyłącznie','Kość promieniowa leży bocznie, po stronie kciuka.','anatomy'],
 ['bones','tibia','Kość piszczelowa','Tibia','tibia','Która kość podudzia przenosi większą część obciążenia osiowego?','kość piszczelowa','kość strzałkowa|rzepka','Piszczel łączy się z kością udową i skokową; strzałka nie tworzy stawu z kością udową.','anatomy'],
 ['bones','joint','Staw maziowy','Synovial joint','articulatio synovialis','Czym pokryte są powierzchnie większości stawów maziowych?','chrząstką szklistą','okostną|tkanką mięśniową','Chrząstka stawowa zmniejsza tarcie i rozkłada obciążenia.','anatomy'],
 ['bones','ligament','Więzadło','Ligament','ligamentum','Co najczęściej łączy więzadło?','kość z kością','mięsień z kością|nerw z mięśniem','Więzadła wspierają stawy i ograniczają nadmierny ruch. Ścięgno łączy zwykle mięsień z kością.','anatomy'],
 ['bones','cervical','Kręgi szyjne','Cervical vertebrae','vertebrae cervicales','Ile kręgów szyjnych ma typowo człowiek?','7','5|12','Odcinek szyjny obejmuje kręgi C1–C7.','anatomy'],
 ['muscle','eccentric','Skurcz ekscentryczny','Eccentric contraction','—','Mięsień wytwarza napięcie i wydłuża się. To praca…','ekscentryczna','koncentryczna|izometryczna','Tak mięsień może hamować ruch, np. czworogłowy podczas kontrolowanego siadania.','anatomy'],
 ['muscle','isometric','Skurcz izometryczny','Isometric contraction','—','Napięcie bez istotnej zmiany długości mięśnia to praca…','izometryczna','koncentryczna|ekscentryczna','W zadaniu izometrycznym wytwarzasz siłę bez widocznego ruchu stawu.','anatomy'],
 ['muscle','concentric','Skurcz koncentryczny','Concentric contraction','—','Aktywny mięsień skraca się podczas pokonywania oporu. To praca…','koncentryczna','ekscentryczna|bierna','Przykład: zginacze łokcia podczas podnoszenia hantla.','anatomy'],
 ['muscle','abduction','Odwodzenie','Abduction','abductio','Ruch ramienia w bok od tułowia nazywamy…','odwodzeniem','przywodzeniem|zgięciem podeszwowym','Odwodzenie oddala segment od płaszczyzny pośrodkowej.','anatomy'],
 ['muscle','dorsiflexion','Zgięcie grzbietowe','Dorsiflexion','dorsiflexio','Przybliżanie grzbietu stopy do podudzia to…','zgięcie grzbietowe','zgięcie podeszwowe|pronacja przedramienia','Zgięcie grzbietowe jest potrzebne m.in. w fazie przenoszenia stopy podczas chodu.','anatomy'],
 ['muscle','gluteus','Mięsień pośladkowy średni','Gluteus medius','musculus gluteus medius','Który mięsień pomaga stabilizować miednicę w staniu na jednej nodze?','pośladkowy średni','dwugłowy ramienia|prostownik palców dłoni','Odwodziciele biodra przeciwdziałają opadaniu miednicy po stronie nogi uniesionej.','anatomy'],
 ['muscle','tendon','Ścięgno','Tendon','tendo','Która struktura przenosi siłę mięśnia na kość?','ścięgno','chrząstka stawowa|błona maziowa','Ścięgno jest zbudowane głównie z uporządkowanej tkanki łącznej bogatej w kolagen.','anatomy'],
 ['muscle','sagittal','Płaszczyzna strzałkowa','Sagittal plane','planum sagittale','Typowe zgięcie i wyprost łokcia zachodzą w płaszczyźnie…','strzałkowej','czołowej|poprzecznej','Płaszczyzna strzałkowa dzieli ciało na części prawą i lewą.','anatomy'],
 ['neuro','neuron','Neuron','Neuron','neuron','Podstawowa pobudliwa komórka układu nerwowego to…','neuron','osteocyt|erytrocyt','Neuron odbiera, przetwarza i przekazuje sygnały.','anatomy'],
 ['neuro','axon','Akson','Axon','axon','Która część neuronu zwykle przewodzi impuls od ciała komórki?','akson','dendryt|jądro komórkowe','Akson prowadzi sygnał do komórek docelowych.','anatomy'],
 ['neuro','myelin','Osłonka mielinowa','Myelin sheath','—','Co zwykle zwiększa szybkość przewodzenia w aksonie?','osłonka mielinowa','brak osłonki|zmniejszenie średnicy zawsze','Mielina umożliwia skokowe przewodzenie między przewężeniami Ranviera.','anatomy'],
 ['neuro','afferent','Droga dośrodkowa','Afferent pathway','—','Informacja czuciowa biegnąca do OUN jest sygnałem…','dośrodkowym','odśrodkowym|wyłącznie hormonalnym','Drogi aferentne doprowadzają informacje do ośrodkowego układu nerwowego.','anatomy'],
 ['neuro','proprioception','Propriocepcja','Proprioception','—','Czucie położenia i ruchu własnych części ciała to…','propriocepcja','termoregulacja|hematopoeza','Współpracują w nim m.in. receptory mięśni, ścięgien i stawów.','anatomy'],
 ['neuro','cerebellum','Móżdżek','Cerebellum','cerebellum','Która struktura szczególnie uczestniczy w koordynacji ruchu i uczeniu motorycznym?','móżdżek','śledziona|tarczyca','Móżdżek porównuje informacje potrzebne do korygowania wykonywanego ruchu.','anatomy'],
 ['neuro','synapse','Synapsa','Synapse','synapsis','Miejsce przekazywania sygnału między neuronem a inną komórką to…','synapsa','sarkomer|osteon','W synapsie chemicznej sygnał przekazuje neuroprzekaźnik.','anatomy'],
 ['neuro','motorunit','Jednostka motoryczna','Motor unit','—','Neuron ruchowy i unerwiane przez niego włókna tworzą…','jednostkę motoryczną','dermatom|krążek międzykręgowy','Rekrutacja jednostek motorycznych pomaga regulować siłę mięśnia.','anatomy'],
 ['breath','diaphragm','Przepona','Diaphragm','diaphragma','Głównym mięśniem spokojnego wdechu jest…','przepona','mięsień żwacz|mięsień naramienny','Przepona podczas skurczu obniża się, zwiększając objętość klatki piersiowej.','anatomy'],
 ['breath','alveoli','Pęcherzyki płucne','Alveoli','alveoli pulmonis','Gdzie zachodzi zasadnicza wymiana gazowa w płucach?','w pęcherzykach płucnych','w tchawicy|w jamie nosowej','Gazy dyfundują przez cienką barierę pęcherzykowo-włośniczkową.','anatomy'],
 ['breath','hemoglobin','Hemoglobina','Hemoglobin','—','Większość tlenu we krwi jest transportowana z…','hemoglobiną','insuliną|kolagenem','Hemoglobina w erytrocytach wiąże tlen odwracalnie.','anatomy'],
 ['breath','atp','ATP','Adenosine triphosphate','—','Bezpośrednim nośnikiem energii wykorzystywanym przez mięśnie jest…','ATP','DNA|bilirubina','Energia z hydrolizy ATP umożliwia m.in. cykl pracy mostków aktyna–miozyna.','anatomy'],
 ['breath','homeostasis','Homeostaza','Homeostasis','—','Utrzymywanie względnie stabilnych warunków wewnętrznych to…','homeostaza','metaplazja|ossyfikacja','Homeostaza opiera się m.in. na układach ujemnego sprzężenia zwrotnego.','anatomy'],
 ['breath','vein','Żyła','Vein','vena','Żyły definiujemy jako naczynia prowadzące krew…','do serca','zawsze od serca|zawsze utlenowaną','Kierunek przepływu definiuje żyłę. Żyły płucne prowadzą krew utlenowaną.','anatomy'],
 ['breath','expiration','Spokojny wydech','Quiet expiration','expiratio','Spokojny wydech w spoczynku jest zwykle…','głównie bierny','zawsze maksymalnym skurczem|niemożliwy bez mięśni brzucha','Sprężysty powrót płuc i klatki piersiowej pomaga wydalić powietrze.','anatomy'],
 ['breath','strokevolume','Objętość wyrzutowa','Stroke volume','—','Ilość krwi wypchnięta przez komorę w jednym skurczu to…','objętość wyrzutowa','pojemność życiowa|częstość oddechów','Pojemność minutowa serca to objętość wyrzutowa pomnożona przez częstość skurczów.','anatomy'],
 ['mind','recall','Aktywne przypominanie','Retrieval practice','—','Co wymaga wydobycia wiedzy z pamięci?','odpowiedź bez podglądania','ponowne podkreślanie|oglądanie gotowej odpowiedzi','Próba samodzielnego odtworzenia pomaga sprawdzić, co rzeczywiście pamiętasz.','memory'],
 ['mind','spacing','Powtórki rozłożone w czasie','Distributed practice','—','Który sposób nauki rozkłada pracę w czasie?','kilka krótkich sesji w różne dni','jedna długa sesja na koniec|jednorazowe przeczytanie','Rozłożona praktyka daje kolejne okazje do przywołania i utrwalenia wiedzy.','memory'],
 ['mind','chunk','Grupowanie','Chunking','—','Łączenie informacji w sensowne grupy nazywamy…','grupowaniem','amnezją|habituacją','Grupy znaczeniowe ułatwiają organizację informacji.','memory'],
 ['mind','elaboration','Opracowanie znaczeniowe','Elaboration','—','Która czynność łączy nową wiedzę z dotychczasową?','wyjaśnienie jej własnym przykładem','kopiowanie bez zrozumienia|liczenie liter','Nadanie znaczenia pomaga stworzyć wskazówki do późniejszego przypomnienia.','memory'],
 ['mind','mnemonic','Mnemotechnika','Mnemonic','—','Akronim pomagający zapamiętać kolejność to…','mnemotechnika','odruch ścięgnisty|pomiar siły','Mnemotechnika jest pomocą w przypominaniu, a nie dowodem zrozumienia.','memory'],
 ['mind','feedback','Informacja zwrotna','Feedback','—','Po błędnej odpowiedzi najbardziej użyteczne jest…','sprawdzenie powodu błędu','ukrycie poprawnej odpowiedzi|losowanie do skutku bez refleksji','Wyjaśnienie pozwala skorygować błędne powiązanie.','memory'],
 ['mind','attention','Uwaga','Attention','—','Co bezpośrednio pomaga skupić się na krótkiej sesji nauki?','ograniczenie rozpraszaczy','równoległe czytanie trzech tekstów|ciągłe sprawdzanie powiadomień','Uwaga ma ograniczone zasoby. Zmiana zadania także wymaga wysiłku.','memory'],
 ['mind','context','Wskazówka pamięciowa','Retrieval cue','—','Hasło pomagające wydobyć wspomnienie to…','wskazówka pamięciowa','receptor bólu|próg tętna','Powiązania znaczeniowe mogą stać się wskazówkami do odtworzenia informacji.','memory'],
 ['nature','cell','Komórka','Cell','cellula','Podstawową jednostką organizacji organizmów jest…','komórka','atom węgla|narząd','Organizmy mogą składać się z jednej komórki albo z wielu wyspecjalizowanych komórek.','biology'],
 ['nature','photo','Fotosynteza','Photosynthesis','—','Który proces wykorzystuje energię światła do tworzenia związków organicznych?','fotosynteza','filtracja|parowanie','W fotosyntezie roślin uwalniany tlen pochodzi z wody.','biology'],
 ['nature','mito','Mitochondrium','Mitochondrion','—','Które organellum ma zasadniczy udział w tlenowej produkcji ATP?','mitochondrium','jąderko|lizosom','W mitochondriach zachodzą kluczowe etapy oddychania komórkowego.','biology'],
 ['nature','fungus','Grzyby','Fungi','Fungi','Do którego królestwa należą drożdże?','grzybów','roślin|zwierząt','Drożdże są grzybami; wiele z nich ma jednokomórkową postać.','biology'],
 ['nature','xylem','Drewno roślinne','Xylem','xylem','Która tkanka przewodzi wodę i sole mineralne w roślinie?','drewno','łyko|naskórek wyłącznie','Drewno, czyli ksylem, tworzy drogę transportu od korzeni.','biology'],
 ['nature','ecosystem','Ekosystem','Ecosystem','—','Organizmy wraz z nieożywionym środowiskiem tworzą…','ekosystem','pojedynczy gatunek|narząd','Ekosystem obejmuje także przepływ energii i obieg materii.','biology'],
 ['nature','dna','DNA','Deoxyribonucleic acid','—','Materiałem genetycznym komórek jest…','DNA','celuloza|hemoglobina','Sekwencja DNA przechowuje informację dziedziczną.','biology'],
 ['nature','diffusion','Dyfuzja','Diffusion','—','Samorzutny przepływ netto cząsteczek zgodnie z gradientem stężenia to…','dyfuzja','transport aktywny|fotosynteza','W prostym ujęciu ruch netto zachodzi od większego do mniejszego stężenia.','biology'],
 ['physics','force','Siła','Force','—','Jednostką siły w SI jest…','niuton','dżul|wat','Niuton to kg·m/s². Siła może zmieniać ruch lub kształt ciała.','physics'],
 ['physics','energy','Energia','Energy','—','Jednostką energii w SI jest…','dżul','niuton|herc','Dżul jest także jednostką pracy mechanicznej.','physics'],
 ['physics','torque','Moment siły','Torque','—','Przy tej samej sile prostopadłej dłuższe ramię daje…','większy moment siły','mniejszy moment siły|zawsze zerowy moment','Moment zależy od siły i jej prostopadłego ramienia.','physics'],
 ['physics','inertia','Bezwładność','Inertia','—','Miarą bezwładności w ruchu postępowym jest…','masa','temperatura|kolor','Większa masa oznacza mniejsze przyspieszenie przy tej samej sile wypadkowej.','physics'],
 ['physics','power','Moc','Power','—','Praca wykonana w jednostce czasu to…','moc','pęd|gęstość','Moc w SI mierzymy w watach.','physics'],
 ['physics','pressure','Ciśnienie','Pressure','—','Przy tej samej sile mniejsze pole nacisku daje…','większe ciśnienie','mniejsze ciśnienie|identyczne ciśnienie zawsze','Ciśnienie to siła nacisku podzielona przez pole powierzchni.','physics'],
 ['physics','frequency','Częstotliwość','Frequency','—','Liczbę pełnych cykli w sekundzie mierzymy w…','hercach','watach|paskalach','1 Hz oznacza jeden cykl na sekundę.','physics'],
 ['physics','lever','Dźwignia','Lever','—','Co zmienia dźwignia?','relację siły i drogi','zasadę zachowania energii|masę planety','Zysk siły w idealnej dźwigni jest okupiony większą drogą działania.','physics'],
 ['care','goal','Cel funkcjonalny','Functional goal','—','Który cel jest najbardziej konkretny funkcjonalnie?','wejść samodzielnie po jednym piętrze','mieć lepszą energię kiedyś|naprawić wszystko','Cel opisujący czynność pozwala śledzić postęp w codziennym działaniu.','nice'],
 ['care','shared','Wspólna decyzja','Shared decision making','—','Co powinno wpływać na wybór postępowania?','cele i preferencje pacjenta','wyłącznie ulubiona metoda terapeuty|sam wygląd zdjęcia','Decyzja uwzględnia sytuację, potrzeby, dowody i preferencje osoby.','nice'],
 ['care','pain','Ból','Pain','dolor','Czy natężenie bólu zawsze odpowiada rozmiarowi uszkodzenia tkanek?','nie','tak, dokładnie|tak, w każdym przewlekłym bólu','Ból jest osobistym doświadczeniem, na które wpływają czynniki biologiczne, psychologiczne i społeczne.','pain'],
 ['care','measure','Pomiar postępu','Outcome measurement','—','Jak najczytelniej porównać postęp konkretnej czynności?','powtórzyć ten sam pomiar w podobnych warunkach','za każdym razem mierzyć coś innego|opierać się tylko na pamięci','Stała metoda ułatwia porównywanie wyników, choć nie usuwa całej zmienności.','nice'],
 ['care','activity','Aktywność','Activity','—','W typowym nieswoistym bólu lędźwi zalecenia promują…','utrzymanie odpowiednio dobranej aktywności','wielotygodniowe leżenie dla każdego|całkowity zakaz ruchu','Dobór aktywności zależy od oceny konkretnej osoby. Gra nie kwalifikuje pacjentów do ćwiczeń.','nice'],
 ['care','imaging','Obrazowanie','Imaging','—','Czy każdy nieswoisty ból lędźwi wymaga rutynowego obrazowania?','nie','tak, zawsze rezonansu|tak, codziennie RTG','Wskazania wynikają z oceny klinicznej i tego, czy wynik może zmienić postępowanie.','nice'],
 ['care','manual','Terapia manualna','Manual therapy','—','W zaleceniach NICE dla bólu lędźwi terapia manualna jest rozważana…','jako część pakietu obejmującego ćwiczenia','wyłącznie jako jedyna metoda|zamiast oceny pacjenta','To zalecenie odnosi się do konkretnego obszaru i nie jest uniwersalną receptą na każdy problem.','nice'],
 ['care','reassess','Ponowna ocena','Reassessment','—','Gdy stan i tolerancja zadania zmieniają się, warto…','ponownie ocenić i dostosować plan','zawsze zwiększyć obciążenie|ignorować zmianę','Plan ma odpowiadać aktualnym możliwościom, reakcji i celom danej osoby.','nice']
];
export const CONCEPTS=rows.map(([world,id,pl,en,latin,question,answer,wrong,explain,source])=>({world,id,pl,en,latin,question,answer,wrong:wrong.split('|'),explain,source}));
export const ORDERS={
 bones:{prompt:'Ułóż regiony kończyny dolnej od tułowia do palców.',steps:['Udo','Podudzie','Stopa']},
 muscle:{prompt:'Ułóż fazy kontrolowanego przysiadu od pozycji stojącej.',steps:['Obniżenie ciała','Dolna pozycja','Powrót do stania']},
 neuro:{prompt:'Ułóż drogę informacji w uproszczonym schemacie reakcji ruchowej.',steps:['Receptor czuciowy','Ośrodkowy układ nerwowy','Mięsień']},
 breath:{prompt:'Ułóż odcinki drogi powietrza od zewnątrz w kierunku płuc.',steps:['Jama nosowa','Tchawica','Oskrzela']},
 mind:{prompt:'Ułóż sensowny cykl nauki po pomyłce.',steps:['Próba odpowiedzi','Wyjaśnienie błędu','Powtórka po przerwie']},
 nature:{prompt:'Ułóż poziomy organizacji organizmu wielokomórkowego.',steps:['Komórka','Tkanka','Narząd']},
 physics:{prompt:'Ułóż jednostki od siły przez energię do mocy.',steps:['Niuton','Dżul','Wat']},
 care:{prompt:'Ułóż uproszczony cykl pracy z celem pacjenta.',steps:['Ocena i cel','Dobór działania','Ponowna ocena']}
};
