import {Engine,SaveStore,SAVE_KEY,clamp} from './engine.js';
import {WORLDS,CLASSES,RELICS,CONCEPTS,ORDERS,SOURCE_LINKS,VERSION} from './content.js';
import {WorldScene} from './scene.js';
import {AudioSystem} from './audio.js';
const $=s=>document.querySelector(s),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const store=new SaveStore(localStorage),engine=new Engine(store.load(),onEvent),actions={x:0,y:0,blocked:true},sound=new AudioSystem(engine.p.settings),scene=new WorldScene(engine,actions);
let modal='',screen='title',selectedWorld=0,challenge=0,busy=false,toastTimer,keys=new Set(),joystickOwner=null,sequence=[],lastFrame=0;
const game=new Phaser.Game({type:Phaser.AUTO,parent:'world',backgroundColor:'#081d23',pixelArt:true,antialias:false,scale:{mode:Phaser.Scale.RESIZE,width:innerWidth,height:innerHeight},scene:[scene],audio:{noAudio:true},fps:{target:60,forceSetTimeOut:false}});
const sprite=(frame,cls='')=>`<span class="portrait ${cls}" style="--sx:${frame%4};--sy:${Math.floor(frame/4)}" aria-hidden="true"></span>`;
const button=(label,action,cls='',disabled=false)=>`<button type="button" class="${cls}" data-action="${action}" ${disabled?'disabled':''}>${label}</button>`;
function save(){try{if(!store.save(engine.p))toast(store.error);}catch(e){toast(e.message);}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function stop(){keys.clear();actions.x=actions.y=0;joystickOwner=null;scene.clearInput();const k=$('#stick-knob');if(k)k.style.transform='translate(0,0)';}
function setModal(name,html,wide=false){stop();modal=name;actions.blocked=true;$('#overlay').innerHTML=`<div class="veil"><section class="panel ${wide?'wide':''}" role="dialog" aria-modal="true" aria-label="${escape(name)}">${html}</section></div>`;$('#overlay button, #overlay input')?.focus({preventScroll:true});}
function closeModal(){if(['quiz','feedback','reward','summary'].includes(modal))return;modal='';$('#overlay').innerHTML='';actions.blocked=screen==='title'||!!engine.r?.battle;stop();}
function forceClose(){modal='';$('#overlay').innerHTML='';actions.blocked=screen==='title'||!!engine.r?.battle;}
const heading=(eyebrow,title,close=true)=>`<div class="panel-head"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2></div>${close?button('×','close','close',''):''}</div>`;
function title(){screen='title';actions.blocked=true;scene.titleMode=true;$('#ui').innerHTML=`<div class="title-shade"></div><section class="title-screen"><p class="eyebrow">SOMASKAN · ORYGINALNE RPG</p><div class="title-rune">✧</div><h1>ATLAS</h1><p class="subtitle">E C H A &nbsp; R U C H U</p><span class="title-line"></span><p class="tagline">Odkryj świat.<br>Niech wiedza stanie się siłą.</p><div class="title-actions">${button(engine.p.counter?'Kontynuuj podróż':'Rozpocznij podróż','play','primary')}${button('Ustawienia','settings','quiet')}</div><p class="version">ROZDZIAŁ I–VIII &nbsp; / &nbsp; ${VERSION} &nbsp; / &nbsp; OFFLINE</p></section><aside class="title-quote">„Nie wszystko, co zagubione,<br>zostało zapomniane.”<small>ORIN, OPIEKUN ATLASU</small></aside>`;}
function enterGame(){screen='game';scene.titleMode=false;forceClose();sound.start();renderHUD();if(engine.r?.finished)showSummary();else if(engine.r?.reward)showReward();else if(engine.r?.battle?.feedback)showFeedback();else if(engine.r?.battle?.quiz)showQuiz();else if(!engine.p.counter)showClasses();}
function renderHUD(){if(screen!=='game')return;const r=engine.r,b=r?.battle,w=engine.world,s=engine.stats();actions.blocked=!!modal||!!b;
 $('#ui').innerHTML=`<header class="hud"><div class="player-status">${sprite(0,'small')}<div><div class="status-label"><b>${CLASSES.find(c=>c.id===engine.p.classId).name}</b><span>POZ. ${engine.level}</span></div><div class="bar hp"><i style="width:${r?r.hp/r.maxHp*100:100}%"></i><span>${r?Math.ceil(r.hp):s.maxHp} / ${r?r.maxHp:s.maxHp}</span></div><div class="focus-row"><span>${'◆'.repeat(r?.focus??6)}<em>${'◇'.repeat(6-(r?.focus??6))}</em></span><small>SKUPIENIE</small></div></div></div><div class="location"><span>${r?w.domain.toUpperCase():'BEZPIECZNA PRZYSTAŃ'}</span><strong>${r?w.name:'Sanktuarium'}</strong><small>${r?`Komnata ${r.stage+1} / 5 · ${r.challenge?'Wyzwanie '+r.challenge:'Podróż'}`:'Osiem krain. Jeden Atlas.'}</small></div><nav>${button('◈ <span>Atlas</span>','atlas','icon-button')}${button('☰ <span>Menu</span>','menu','icon-button')}</nav></header>
 ${b?battleHUD():`<div class="objective"><span class="objective-dot"></span><div><small>TWÓJ CEL</small><b>${r?(engine.objectDone('enemy')?'Odkryj skrytki lub wejdź w portal':r.stage===4?'Pokonaj Strażnika tej krainy':'Odkryj komnatę i ucisz echo'):'Porozmawiaj z Orinem lub rozpocznij wyprawę'}</b></div></div><canvas id="minimap" width="150" height="114" aria-label="Minimapa komnaty"></canvas><div class="run-pocket">${r?`◈ ${r.gold} <span>·</span> Eliksiry ${r.potions} <span>·</span> Relikty ${r.relics.length}`:`◈ ${engine.p.gold} <span>·</span> Pieczęcie ${engine.p.cleared.length}/8`}</div><div id="joystick" aria-label="Joystick ruchu"><span id="stick-knob"></span><i>RUCH</i></div><div class="field-actions">${!r?button('Wyprawa ↗','worlds','primary compact'):button('Relikty','relics','quiet compact')}<button id="interact" data-action="interact" class="interact" disabled><span>◇</span><small>PODEJDŹ</small></button></div><p class="control-hint">Dotknij ścieżki, aby iść · WASD / strzałki · E: interakcja</p>`}`;
 if(!b){bindJoystick();drawMinimap();}if(b)scene.battle(true);
}
function battleHUD(){const r=engine.r,b=r.battle,i=engine.intent(),w=engine.world,cost=engine.p.classId==='seeker'?2:3;const analysisAvailable=b.turn>=b.analysisReady&&CONCEPTS.some(c=>c.world===r.world&&!r.quizUsed.includes(c.id));
 return `<section class="enemy-status"><p class="eyebrow">${b.boss?'STRAŻNIK KRAINY':'ECHO KRAINY'} · ${b.boss?'FAZA '+b.phase:'TURA '+(b.turn+1)}</p><h2>${b.boss?w.boss:'Echo · '+w.domain}</h2><div class="bar enemy"><i style="width:${b.hp/b.maxHp*100}%"></i><span>${b.hp} / ${b.maxHp}</span></div></section><div class="intent ${i.type}"><span>${i.type==='heavy'?'⚠':'◇'}</span><div><small>ZAMIAR PRZECIWNIKA</small><b>${i.name}${i.damage?' · '+i.damage+' obrażeń':''}</b><p>${i.hint}</p></div></div><div class="combat-log" aria-live="polite">${b.log.map(l=>`<p>${l}</p>`).join('')}</div><section class="combat-actions"><div class="turn-label"><span>TWOJA TURA</span><small>Wróg czeka na twoją decyzję.</small></div><div class="command-row">${button('<strong>Cięcie</strong><small>+1 skupienia</small>','attack','command')}${button('<strong>Osłona</strong><small>Ochrona · +2 skupienia</small>','guard','command')}${button(`<strong>Technika</strong><small>Przebicie · ${cost} skupienia</small>`,'tech','command',r.focus<cost)}${engine.p.settings.mode==='learning'?button('<strong>Analiza</strong><small>Wiedza przerywa atak</small>','analysis','command knowledge',!analysisAvailable):button('<strong>Relikty</strong><small>Sprawdź swój zestaw</small>','relics','command')}${button(`<strong>Eliksir</strong><small>+38 zdrowia · ${r.potions} szt.</small>`,'potion','command',r.potions<1)}</div></section>`;
}
function showClasses(){setModal('Początek podróży',heading('TWÓJ STYL GRY','Kim będzie wędrowiec?',false)+`<p class="lede">Orin powierza ci latarnię. Wybierz talent, z którym wejdziesz do Atlasu.</p><div class="class-row">${CLASSES.map((c,i)=>button(`${sprite(i)}<h3>${c.name}</h3><p class="gold">${c.subtitle}</p><p>${c.desc}</p>`,`class:${c.id}`,'class-option')).join('')}</div><p class="footnote">Możesz grać z nauką lub bez pytań. Zmienisz to w ustawieniach.</p>`,true);}
function worlds(){selectedWorld=Math.min(selectedWorld,engine.p.unlocked);const w=WORLDS[selectedWorld];setModal('Wybór krainy',heading('OSIEM FRAGMENTÓW ATLASU','Dokąd zaprowadzi cię latarnia?')+`<div class="world-selector"><div class="world-list">${WORLDS.map((v,i)=>button(`<span class="world-number">${String(i+1).padStart(2,'0')}</span><span><b>${v.name}</b><small>${v.domain}</small></span><em>${engine.p.cleared.includes(v.id)?'✦':i>engine.p.unlocked?'⌑':'→'}</em>`,`world:${i}`,i===selectedWorld?'selected':'',i>engine.p.unlocked)).join('')}</div><div class="world-detail">${sprite(w.sprite,'large')}<p class="eyebrow">${w.domain}</p><h3>${w.name}</h3><p>${w.story}</p><div class="world-rule">${w.rule}</div>${engine.p.cleared.includes(w.id)?`<label class="select-label">Wyzwanie <select id="challenge"><option value="0">Spokojna podróż</option><option value="1">I · silniejsze echa</option><option value="2">II · próba odwagi</option><option value="3">III · mistrzostwo</option></select></label>`:''}${button('Wejdź do krainy ↗','start','primary')}</div></div>`,true);}
function showQuiz(){const b=engine.r.battle,q=b.quiz,c=CONCEPTS.find(c=>c.id===q.id);sequence=[];const prompt=q.type==='order'?ORDERS[engine.r.world].prompt:c.question;setModal('Analiza',heading(q.type==='recall'?'PRZYWOŁAJ Z PAMIĘCI':q.type==='order'?'UŁÓŻ KOLEJNOŚĆ':'ODCZYTAJ ECHO','Zrozum. Przerwij. Zwyciężaj.',false)+`<p class="question">${escape(prompt)}</p>${q.type==='recall'?`<form id="recall-form"><label for="recall">Twoja odpowiedź</label><input id="recall" autocomplete="off" placeholder="Wpisz odpowiedź…" maxlength="120"><button class="primary" type="submit">Sprawdź odpowiedź</button></form>`:q.type==='order'?`<div id="sequence-answer" class="sequence-answer">Dotykaj pojęć we właściwej kolejności.</div><div class="answers">${q.options.map((o,i)=>button(escape(o),'sequence:'+i,'answer')).join('')}</div><div class="panel-actions">${button('Od początku','sequence-reset','quiet')}${button('Sprawdź sekwencję','sequence-submit','primary',true)}</div>`:`<div class="answers">${q.options.map((o,i)=>button(`<span>${String.fromCharCode(65+i)}</span>${escape(o)}`,'answer:'+i,'answer')).join('')}</div>`}<p class="footnote">Bez limitu czasu. Trafienie przerywa zamiar wroga. Błąd dostaje wyjaśnienie.</p>${button('Wróć do taktyki','quiz-cancel','quiet')}`);
 $('#recall-form')?.addEventListener('submit',e=>{e.preventDefault();const value=$('#recall').value.trim();if(value)engine.answer(value);});}
function showFeedback(){const f=engine.r.battle.feedback,c=CONCEPTS.find(c=>c.id===f.conceptId);setModal('Wyjaśnienie',heading(f.correct?'ECHO ROZPOZNANE':'NOWA WSKAZÓWKA',f.correct?'Wiedza staje się siłą.':'Zatrzymaj sens, nie pomyłkę.',false)+`<div class="feedback-mark ${f.correct?'correct':''}">${f.correct?'✦':'◇'}</div><p class="correct-answer">${escape(f.expected)}</p><p class="lede">${f.type==='order'?'Ta kolejność przedstawia uproszczony porządek omawianego procesu.':escape(c.explain)}</p>${f.type!=='order'?`<div class="term"><b>${c.pl}</b><span>EN: ${c.en}${c.latin!=='—'?' · ŁAC: '+c.latin:''}</span></div>`:''}<p class="footnote">${f.correct?'Przerywasz następny ruch przeciwnika i wzmacniasz uderzenie.':'To pojęcie wróci w powtórkach. Błąd nie odbiera zdobytego doświadczenia.'}</p>${button('Wróć do walki','resolve-answer','primary')}`);sound.effect(f.correct?'win':'wrong');}
function showReward(){const reward=engine.r.reward;setModal('Relikt',heading('ZMIEŃ SPOSÓB GRY',reward.title,false)+`<p class="lede">Wybierz jeden. Efekt działa do końca tej wyprawy.</p><div class="relic-row">${reward.choices.map(id=>{const r=RELICS.find(r=>r.id===id);return button(`<span class="relic-symbol">${r.symbol}</span><small>${r.rarity}</small><h3>${r.name}</h3><p>${r.desc}</p>`,'relic:'+id,'relic-option');}).join('')}</div>`,true);}
function showRelics(){const ids=engine.r?.relics||engine.p.relics;setModal('Relikty',heading(engine.r?'AKTYWNE W TEJ WYPRAWIE':'ODKRYTA KOLEKCJA','Relikty wędrowca')+`<div class="relic-list">${ids.length?ids.map(id=>{const r=RELICS.find(x=>x.id===id);return `<article><span class="relic-symbol">${r.symbol}</span><div><h3>${r.name}</h3><p>${r.desc}</p></div></article>`;}).join(''):'<p class="lede">Otwieraj skrzynie, aby znaleźć pierwszy relikt. Łącz ich działanie z wybranym stylem walki.</p>'}</div>`);}
function showRoute(){setModal('Droga',heading('NASTĘPNA KOMNATA','Każda droga ma swoją cenę.')+`<div class="route-row">${button('<span>♧</span><h3>Ścieżka oddechu</h3><p>Odzyskaj 20 zdrowia. Spokojna droga.</p>','route:rest','route-option')}${button('<span>ϟ</span><h3>Ścieżka odwagi</h3><p>+15 monet. Następne echo ma +16 zdrowia.</p>','route:risk','route-option')}${button('<span>◇</span><h3>Ścieżka równowagi</h3><p>Zachowaj siły i odkryj kolejną komnatę.</p>','route:balanced','route-option')}</div>`,true);}
function showSummary(){const r=engine.r,w=engine.world,report=engine.p.history[0];if(!r?.finished||!report)return;setModal('Wynik wyprawy',heading(report.win?'PIECZĘĆ ODZYSKANA':'LATARNIA WCIĄŻ PŁONIE',report.win?'Kraina znów pamięta.':'To jeszcze nie koniec podróży.',false)+`<div class="summary-art">${sprite(w.sprite,'large')}</div><p class="lede">${report.win?w.ending:'Orin sprowadza cię do Sanktuarium. Zachowujesz zdobyte monety, doświadczenie i odkrytą wiedzę.'}</p><div class="summary-stats"><div><b>+${report.xp}</b><small>DOŚWIADCZENIA</small></div><div><b>+${report.gold}</b><small>MONET</small></div><div><b>${report.answers?report.correct+'/'+report.answers:'—'}</b><small>TRAFNE ANALIZY</small></div><div><b>${report.secrets}</b><small>SEKRETÓW</small></div></div>${button('Wróć do Sanktuarium','home','primary')}`,true);}
function atlas(filter=''){const entries=CONCEPTS.filter(c=>(!filter||normalText(c.pl+' '+c.en+' '+c.latin).includes(normalText(filter))));setModal('Atlas wiedzy',heading('PL · EN · ŁACINA','Atlas odkryć')+`<label class="search-label"><span>Szukaj pojęcia</span><input id="atlas-search" value="${escape(filter)}" placeholder="np. przepona, femur, siła…"></label><div class="atlas-list">${entries.map(c=>{const k=engine.p.knowledge[c.id];return `<details><summary><span><b>${c.pl}</b><small>${c.en}${c.latin!=='—'?' · '+c.latin:''}</small></span><em>${k?(k.streak>=3?'✦':k.wrong?'↻':'◇'):'·'}</em></summary><p>${c.explain}</p><p class="source">Źródło odniesienia: ${SOURCE_LINKS[c.source].title}</p>${k?`<small>Poprawne: ${k.right} · Pomyłki: ${k.wrong} · Seria: ${k.streak}</small>`:''}</details>`;}).join('')}</div><p class="footnote">64 pojęcia i 8 sekwencji. Treść edukacyjna, nie instrukcja leczenia pacjenta.</p>`,true);$('#atlas-search').addEventListener('input',e=>{const v=normalText(e.target.value);document.querySelectorAll('.atlas-list details').forEach(el=>el.hidden=!normalText(el.textContent).includes(v));});}
const normalText=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function menu(){setModal('Menu',heading('PRZERWA W PODRÓŻY','Latarnia poczeka.')+`<div class="menu-grid">${button('Wróć do gry','close','primary')}${button('Atlas pojęć','atlas')}${button(engine.r?'Aktywne relikty':'Kolekcja reliktów','relics')}${button('Powtórz pomyłki','review')}${!engine.r?button('Rozwój postaci','forge'):''}${button('Ustawienia i zapis','settings')}${engine.r&&!engine.r.finished?button('Zakończ wyprawę','abandon-confirm','danger'):button('Ekran tytułowy','title')}</div><p class="footnote">Postęp zapisuje się automatycznie. ${store.error||''}</p>`);save();}
function settings(){const s=engine.p.settings;setModal('Ustawienia',heading('GRA PO TWOJEMU','Ustawienia i zapis')+`<div class="settings-list"><label><span>Dźwięki otoczenia i efekty</span><input type="checkbox" data-setting="sound" ${s.sound?'checked':''}></label><label><span>Muzyka</span><input type="checkbox" data-setting="music" ${s.music?'checked':''}></label><label><span>Ruch kamery i efekty</span><input type="checkbox" data-setting="motion" ${s.motion?'checked':''}></label><label><span>Styl przygody</span><select data-setting="mode"><option value="learning" ${s.mode==='learning'?'selected':''}>Przygoda + wiedza</option><option value="adventure" ${s.mode==='adventure'?'selected':''}>Sama przygoda</option></select></label><label><span>Tekst</span><select data-setting="text"><option value="1" ${s.text===1?'selected':''}>Standardowy</option><option value="1.15" ${s.text===1.15?'selected':''}>Większy</option></select></label></div><div class="panel-actions">${button('Eksportuj zapis','export','primary')}${button('Importuj zapis','import','quiet')}</div><input type="file" id="import-file" accept="application/json,.json" hidden><p class="footnote">Atlas — Echa Ruchu ${VERSION}. Nowa gra z osobnym zapisem; pliki poprzedniego FizjoRPG 3.x nie są zgodne.</p>`);document.querySelectorAll('[data-setting]').forEach(el=>el.addEventListener('change',()=>{const k=el.dataset.setting;s[k]=el.type==='checkbox'?el.checked:k==='text'?Number(el.value):el.value;document.documentElement.style.setProperty('--text-scale',s.text);sound.start();save();renderHUD();}));$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const p=store.import(await file.text());engine.p=p;engine.makeMap();sound.settings=p.settings;scene.mapKey='';forceClose();enterGame();toast('Wczytano zapis.');}catch(err){toast(err.message);}});}
function forge(){setModal('Rozwój postaci',heading('SANKTUARIUM','Siła z każdej wyprawy')+`<p class="lede">Masz ${engine.p.gold} monet. Ulepszenia są trwałe.</p><div class="route-row">${['vitality','power'].map(k=>{const n=engine.p.talents[k],cost=60+n*35;return button(`<span>${k==='vitality'?'♡':'ϟ'}</span><h3>${k==='vitality'?'Witalność':'Precyzja'} ${n}/10</h3><p>${k==='vitality'?'+8 maksymalnego zdrowia':'+2 siły ataku'}</p><b>${cost} monet</b>`,'upgrade:'+k,'route-option',n>=10||engine.p.gold<cost);}).join('')}</div>`);}
function merchant(){setModal('Orin',heading('WĘDROWNY OPIEKUN','Co przyda się w drodze?')+`<p class="lede">„Nie musisz być gotów na wszystko. Wystarczy kolejny dobry krok.”</p><p>Monety tej wyprawy: <b>${engine.r.gold}</b></p><div class="route-row">${button('<h3>Eliksir</h3><p>Jedna dodatkowa mikstura.</p><b>25 monet</b>','buy:potion','route-option',engine.r.gold<25||engine.objectDone('bought:potion'))}${button('<h3>Odpoczynek</h3><p>Odzyskaj 45 zdrowia.</p><b>40 monet</b>','buy:rest','route-option',engine.r.gold<40||engine.objectDone('bought:rest'))}</div>`);}
function review(){const due=CONCEPTS.filter(c=>engine.p.knowledge[c.id]&&(engine.p.knowledge[c.id].wrong||engine.p.knowledge[c.id].due<=Date.now()));setModal('Powtórki',heading('BEZ PRESJI I BEZ FARMY XP','Pamięć potrzebuje powrotów')+`<div class="atlas-list">${due.length?due.map(c=>`<details><summary><b>${c.question}</b></summary><h3>${c.answer}</h3><p>${c.explain}</p><small>Spróbuj odpowiedzieć przed odsłonięciem.</small></details>`).join(''):'<p class="lede">Nie masz jeszcze pojęć do powtórki. Echa z błędnych odpowiedzi pojawią się tutaj.</p>'}</div><p class="footnote">Samo odkrywanie odpowiedzi nie zwiększa XP ani opanowania pojęcia. Postęp mierzą odpowiedzi w wyprawach.</p>`);}
function onEvent(e){if(!scene)return;save();if(e.event==='notice'){toast(e.text);return;}if(e.event==='turn'){forceClose();scene.hit(e);sound.effect('hit');renderHUD();return;}forceClose();renderHUD();switch(e.event){case 'portal':worlds();break;case 'mentor':setModal('Orin',heading('OPIEKUN ATLASU','Witaj, wędrowcze.')+`<p class="lede">„Osiem krain utraciło pamięć. Zbieraj relikty, odczytuj echa i obserwuj zamiary Strażników. Twoja latarnia rozświetli drogę.”</p><p>Dotknij podłogi lub użyj joysticka. Dotknij postaci albo podejdź i naciśnij przycisk interakcji.</p>${button('Wybierz pierwszą krainę','worlds','primary')}`);break;case 'forge':forge();break;case 'library':atlas();break;case 'merchant':merchant();break;case 'quiz':showQuiz();break;case 'feedback':showFeedback();break;case 'reward':showReward();break;case 'route':showRoute();break;case 'summary':sound.effect('win');showSummary();break;case 'lore':setModal('Echo wiedzy',heading('FRAGMENT ATLASU',e.concept.pl)+`<p class="lede">${e.concept.explain}</p><div class="term"><b>${e.concept.en}</b><span>${e.concept.latin}</span></div><p>Skupienie odnowione do pełna.</p>${button('Zachowaj w pamięci','close','primary')}`);break;case 'secret':sound.effect('relic');toast(e.text);break;case 'victory':sound.effect('win');toast(`Echo uciszone. +${e.xp} XP · +${e.gold} monet. Poszukaj skrzyni lub portalu.`);break;case 'relic':sound.effect('relic');toast('Relikt dołączony. Jego moc już działa.');break;case 'start':toast(engine.world.story);break;case 'stage':toast('Komnata '+(engine.r.stage+1)+'. Rozejrzyj się za sekretem.');break;}}
function drawMinimap(){const c=$('#minimap');if(!c)return;const ctx=c.getContext('2d'),m=engine.map,r=engine.r,seen=new Set(r?.seen||[]);ctx.clearRect(0,0,150,114);ctx.fillStyle='#071a21cc';ctx.fillRect(0,0,150,114);for(let y=0;y<m.height;y++)for(let x=0;x<m.width;x++){if(m.tiles[y][x]){ctx.fillStyle=!r||seen.has(y*m.width+x)?'#547c78':'#183039';ctx.fillRect(x*6,y*6,5,5);}}for(const o of m.objects)if(!o.secret&&!engine.objectDone(o.id)&&(!r||seen.has(o.y*m.width+o.x))){ctx.fillStyle=o.kind==='enemy'?'#f69f83':o.kind==='exit'||o.kind==='portal'?'#87e6d3':'#e8c688';ctx.fillRect(o.x*6,o.y*6,5,5);}ctx.fillStyle='#fff4cd';ctx.beginPath();ctx.arc(engine.position.x*6+3,engine.position.y*6+3,3,0,7);ctx.fill();}
actions.onFrame=()=>{if(performance.now()-lastFrame<150)return;lastFrame=performance.now();if(screen==='game'&&!engine.r?.battle){const o=engine.nearest(),b=$('#interact');if(b){b.disabled=!o;b.querySelector('small').textContent=o?o.label:'PODEJDŹ';}drawMinimap();}};
function bindJoystick(){const el=$('#joystick');if(!el)return;const move=e=>{if(e.pointerId!==joystickOwner)return;const box=el.getBoundingClientRect(),dx=e.clientX-box.left-box.width/2,dy=e.clientY-box.top-box.height/2,len=Math.hypot(dx,dy),max=box.width*.3;actions.x=len>8?dx/Math.max(max,len):0;actions.y=len>8?dy/Math.max(max,len):0;$('#stick-knob').style.transform=`translate(${clamp(dx,-max,max)}px,${clamp(dy,-max,max)}px)`;};el.addEventListener('pointerdown',e=>{if(actions.blocked||joystickOwner!==null)return;joystickOwner=e.pointerId;el.setPointerCapture(e.pointerId);e.preventDefault();move(e);});el.addEventListener('pointermove',move);for(const name of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(name,e=>{if(e.pointerId===joystickOwner)stop();});}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const [a,arg]=b.dataset.action.split(':');sound.start();sound.effect('click');
 if(['attack','guard','tech','potion'].includes(a)){if(busy)return;busy=true;engine.action(a);setTimeout(()=>busy=false,350);return;}
 switch(a){case 'play':enterGame();break;case 'class':engine.p.classId=arg;forceClose();engine.start('bones');break;case 'close':closeModal();break;case 'worlds':worlds();break;case 'world':selectedWorld=Number(arg);worlds();break;case 'start':challenge=Number($('#challenge')?.value||0);forceClose();engine.start(WORLDS[selectedWorld].id,Date.now()>>>0,challenge);break;case 'interact':engine.interact();break;case 'menu':menu();break;case 'title':forceClose();save();title();break;case 'atlas':atlas();break;case 'settings':settings();break;case 'review':review();break;case 'relics':showRelics();break;case 'forge':forge();break;case 'upgrade':engine.upgrade(arg);forge();break;case 'buy':engine.buy(arg);merchant();break;case 'analysis':engine.question();break;case 'answer':engine.answer(engine.r.battle.quiz.options[Number(arg)]);break;case 'quiz-cancel':engine.r.battle.quiz=null;forceClose();renderHUD();save();break;case 'resolve-answer':engine.resolveAnswer();break;case 'sequence':{const q=engine.r.battle.quiz;sequence.push(q.options[Number(arg)]);b.disabled=true;$('#sequence-answer').textContent=sequence.join(' → ');$('[data-action="sequence-submit"]').disabled=sequence.length!==3;break;}case 'sequence-reset':showQuiz();break;case 'sequence-submit':engine.answer(sequence);break;case 'relic':engine.chooseRelic(arg);break;case 'route':forceClose();engine.advance(arg);break;case 'home':engine.home();break;case 'abandon-confirm':setModal('Powrót',heading('ZAKOŃCZENIE WYPRAWY','Wracasz do Sanktuarium?')+`<p class="lede">Zachowasz zdobyte monety, wiedzę i doświadczenie. Ta wyprawa zostanie zakończona.</p>${button('Zakończ i wróć','abandon','primary')}${button('Graj dalej','close','quiet')}`);break;case 'abandon':engine.abandon();break;case 'export':{const text=JSON.stringify(engine.p,null,2);if(window.AndroidBridge?.saveTextFile)window.AndroidBridge.saveTextFile('Atlas-Echa-Ruchu-zapis.json',text);else{const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='Atlas-Echa-Ruchu-zapis.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}break;}case 'import':$('#import-file').click();break;}
});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.key==='Escape'){if(modal)closeModal();else if(screen==='game')menu();return;}if(actions.blocked)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','w','a','s','d','W','A','S','D','e','E'].includes(e.key))e.preventDefault();if(e.key.toLowerCase()==='e'||e.key===' '){if(!e.repeat)engine.interact();return;}keys.add(e.key.toLowerCase());keyboard();});document.addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());keyboard();});
function keyboard(){actions.x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);actions.y=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);}
window.addEventListener('blur',()=>{stop();save();sound.pause();});document.addEventListener('visibilitychange',()=>{stop();save();if(document.hidden)sound.pause();else if(screen==='game')sound.start();});document.addEventListener('atlas:pause',()=>{stop();save();sound.pause();});document.addEventListener('atlas:back',()=>{if(modal)closeModal();else if(screen==='game')menu();});window.addEventListener('beforeunload',save);setInterval(()=>{if(screen==='game')save();},5000);
document.documentElement.style.setProperty('--text-scale',engine.p.settings.text);title();if(store.recovered)toast('Przywrócono ostatnią poprawną kopię zapisu.');
// Read-only QA state, no mutation hooks or rewards exposed to the UI.
window.atlasState=()=>JSON.parse(JSON.stringify({screen,modal,profile:engine.p,position:engine.position,mapSignature:engine.map.signature,version:VERSION,objects:scene.ready?engine.map.objects.map(o=>({...o,done:engine.objectDone(o.id),screenX:((o.x+.5)*48-scene.cameras.main.worldView.x)*scene.cameras.main.zoom,screenY:((o.y+.5)*48-scene.cameras.main.worldView.y)*scene.cameras.main.zoom})):[]}));
