import {pathTo,clamp} from './engine.js';
const TILE=48;
export class WorldScene extends Phaser.Scene{
 constructor(engine,input){super('World');this.engine=engine;this.actions=input;this.mapKey='';this.path=[];this.actorViews=[];this.battleViews=null;this.titleMode=true;this.elapsed=0;}
 preload(){this.load.spritesheet('actors','assets/sprites/actors.png',{frameWidth:128,frameHeight:128});this.load.spritesheet('environment','assets/environment/world.png',{frameWidth:128,frameHeight:128});this.load.spritesheet('hero','assets/sprites/hero-walk.png',{frameWidth:96,frameHeight:96});}
 create(){for(let d=0;d<4;d++)this.anims.create({key:'walk'+d,frames:this.anims.generateFrameNumbers('hero',{start:d*4,end:d*4+3}),frameRate:8,repeat:-1});
  const dot=this.make.graphics({x:0,y:0,add:false});dot.fillStyle(0xffffff);dot.fillCircle(3,3,3);dot.generateTexture('dot',6,6);dot.destroy();this.cameras.main.setBackgroundColor('#081d23');this.buildMap();
  this.input.on('pointerup',p=>{if(this.actions.blocked||this.titleMode||this.engine.r?.battle||p.getDistance()>18)return;const v=this.cameras.main.getWorldPoint(p.x,p.y),x=v.x/TILE-.5,y=v.y/TILE-.5;let target=this.engine.map.objects.filter(o=>!this.engine.objectDone(o.id)).find(o=>Math.hypot(o.x-x,o.y-y)<.9);this.targetObject=target||null;this.path=pathTo(this.engine.map,this.engine.position,target||{x,y});if(this.path.length)this.marker.setPosition((Math.round(x)+.5)*TILE,(Math.round(y)+.5)*TILE).setVisible(true);});
  this.scale.on('resize',()=>this.resize());this.ready=true;this.resize();document.getElementById('boot')?.remove();}
 buildMap(){this.worldLayer?.destroy(true);this.worldLayer=this.add.container(0,0);this.actorViews=[];const m=this.engine.map,w=this.engine.world;
  const floor=this.add.renderTexture(0,0,m.width*TILE,m.height*TILE).setOrigin(0);floor.fill(0x0c252b);this.worldLayer.add(floor);const stamp=this.make.image({x:0,y:0,key:'environment',add:false}).setOrigin(0).setDisplaySize(TILE,TILE);
  for(let y=0;y<m.height;y++)for(let x=0;x<m.width;x++){const t=m.tiles[y][x];stamp.setFrame(t?(this.engine.r?w.floor:0):(w.shape==='islands'?3:2));stamp.setTint(t?0xffffff:0x355461);stamp.setAlpha(t?1:.38);floor.draw(stamp,x*TILE,y*TILE);}stamp.destroy();
  const edges=this.add.graphics();this.worldLayer.add(edges);for(let y=1;y<m.height-1;y++)for(let x=1;x<m.width-1;x++)if(m.tiles[y][x]){if(!m.tiles[y+1]?.[x]){edges.fillStyle(0x040e13,.8);edges.fillRect(x*TILE,(y+1)*TILE-3,TILE,8);}if(!m.tiles[y-1]?.[x]){edges.lineStyle(1,0xacdbca,.3);edges.lineBetween(x*TILE,y*TILE,(x+1)*TILE,y*TILE);}}
  const decorations=[...m.props];if(!this.engine.r)decorations.push({x:12,y:9,frame:11},{x:5,y:3,frame:4},{x:20,y:3,frame:4},{x:3,y:11,frame:8},{x:21,y:14,frame:8},{x:9,y:5,frame:13});
  for(const p of decorations){const prop=this.add.image((p.x+.5)*TILE,(p.y+1)*TILE,'environment',p.frame).setOrigin(.5,1).setDisplaySize(90,90).setDepth(p.y*TILE+20);this.worldLayer.add(prop);}
  for(const o of m.objects){const shadow=this.add.ellipse((o.x+.5)*TILE,(o.y+.85)*TILE,38,13,0x020b0e,.5),size=o.kind==='enemy'?(o.boss?112:78):o.kind==='portal'||o.kind==='exit'?112:o.kind==='lore'?90:72;const view=this.add.sprite((o.x+.5)*TILE,(o.y+.85)*TILE,o.env!==undefined?'environment':'actors',o.env??o.sprite).setOrigin(.5,1).setDisplaySize(size,size);this.worldLayer.add([shadow,view]);view.setDepth(o.y*TILE+25);shadow.setDepth(o.y*TILE+10);
   const label=this.add.text((o.x+.5)*TILE,(o.y-.8)*TILE,o.kind==='enemy'?(o.boss?'STRAŻNIK':'ECHO'):o.kind==='exit'?'PRZEJŚCIE':o.kind==='portal'?'WYPRAWA':'',{fontFamily:'Arial',fontSize:'10px',color:'#ead7a8',stroke:'#081e23',strokeThickness:4}).setOrigin(.5).setDepth(o.y*TILE+100);this.worldLayer.add(label);this.actorViews.push({o,view,shadow,label,baseY:view.y,size});}
  this.heroShadow=this.add.ellipse(0,0,29,10,0x020b0e,.6);this.hero=this.add.sprite(0,0,'hero',0).setOrigin(.5,.92).setDisplaySize(73,73);this.companion=this.add.sprite(0,0,'actors',15).setDisplaySize(38,38);this.worldLayer.add([this.heroShadow,this.hero,this.companion]);this.marker=this.add.graphics();this.marker.lineStyle(2,0xd9c28b,.85);this.marker.strokeCircle(0,0,13);this.marker.setVisible(false);this.worldLayer.add(this.marker);this.marker.setDepth(2);this.mist=this.add.graphics().setDepth(5000);this.worldLayer.add(this.mist);
  this.particles=this.add.particles(0,0,'dot',{x:{min:50,max:m.width*TILE-50},y:{min:40,max:m.height*TILE-50},lifespan:5000,frequency:180,speedY:{min:-9,max:-3},speedX:{min:-4,max:4},scale:{start:.32,end:0},alpha:{start:0,end:.6},tint:[0x86ddbe,0xe8d4a0],blendMode:'ADD'});this.worldLayer.add(this.particles);this.particles.setDepth(6000);this.worldLayer.sort('depth');this.cameras.main.setBounds(0,0,m.width*TILE,m.height*TILE);this.path=[];this.targetObject=null;this.mapKey=`${this.engine.r?.id||0}:${this.engine.r?.stage||0}`;this.lastFogX=null;this.positionHero();this.resize();}
 positionHero(){if(!this.hero)return;const p=this.engine.position;this.hero.setPosition((p.x+.5)*TILE,(p.y+.8)*TILE);this.heroShadow.setPosition(this.hero.x,this.hero.y-2);this.hero.setDepth(this.hero.y+10);this.heroShadow.setDepth(this.hero.y-5);this.companion.setPosition(this.hero.x-32,this.hero.y-48+Math.sin(this.elapsed/400)*5).setDepth(this.hero.y+5);}
 resize(){const c=this.cameras.main;if(!this.hero)return;const zoom=clamp(Math.min(this.scale.width/960,this.scale.height/510)*1.2,.65,1.5);c.setZoom(zoom);c.startFollow(this.hero,true,.12,.12,0,35);this.layoutBattle();}
 battle(show){if(show&&!this.battleViews){this.cameras.main.setZoom(1);const layer=this.add.container(0,0).setDepth(10000).setScrollFactor(0),shade=this.add.rectangle(0,0,1,1,0x04151d,.86).setOrigin(0),circle=this.add.ellipse(0,0,350,100,0x487b73,.15).setStrokeStyle(1,0xc4b585,.3),hero=this.add.sprite(0,0,'actors',1).setOrigin(.5,1),enemy=this.add.sprite(0,0,'actors',this.engine.world.sprite).setOrigin(.5,1),heroShadow=this.add.ellipse(0,0,115,20,0x000000,.35),enemyShadow=this.add.ellipse(0,0,180,28,0x000000,.4);layer.add([shade,circle,heroShadow,enemyShadow,hero,enemy]);this.battleViews={layer,shade,circle,hero,enemy,heroShadow,enemyShadow};this.layoutBattle();}if(!show&&this.battleViews){this.battleViews.layer.destroy(true);this.battleViews=null;this.resize();}}
 layoutBattle(){const b=this.battleViews;if(!b)return;const cam=this.cameras.main,z=cam.zoom,w=this.scale.width/z,h=this.scale.height/z;b.shade.setSize(w,h);b.circle.setPosition(w*.5,h*.66).setDisplaySize(w*.62,h*.18);const size=Math.min(h*.47,w*.25);b.hero.setPosition(w*.31,h*.70).setDisplaySize(size*.78,size*.78);b.enemy.setPosition(w*.69,h*.67).setDisplaySize(size*1.08,size*1.08);b.heroShadow.setPosition(b.hero.x,b.hero.y-3).setDisplaySize(size*.65,18);b.enemyShadow.setPosition(b.enemy.x,b.enemy.y-3).setDisplaySize(size*.8,22);b.heroBaseX=b.hero.x;b.enemyBaseY=b.enemy.y;}
 hit(event){if(!this.battleViews)return;const b=this.battleViews;if(event.damage){b.enemy.setTint(0xffc7a0);this.time.delayedCall(160,()=>b.enemy?.active&&b.enemy.clearTint());if(this.engine.p.settings.motion)this.tweens.add({targets:b.hero,x:b.heroBaseX+20,duration:90,yoyo:true});this.floatText(`−${event.damage}`,b.enemy.x,b.enemy.y-120,'#f5d49b');}if(event.taken){this.floatText(`−${event.taken}`,b.hero.x,b.hero.y-95,'#ffb3a0');if(this.engine.p.settings.motion)this.cameras.main.shake(90,.002);}}
 floatText(text,x,y,color){const t=this.add.text(x,y,text,{fontFamily:'Georgia',fontSize:'28px',fontStyle:'bold',color,stroke:'#09232b',strokeThickness:5}).setOrigin(.5).setScrollFactor(0).setDepth(11000);this.tweens.add({targets:t,y:y-35,alpha:0,duration:950,onComplete:()=>t.destroy()});}
 clearInput(){this.path=[];this.targetObject=null;this.actions.x=0;this.actions.y=0;this.marker?.setVisible(false);}
 update(time,delta){if(!this.ready)return;this.elapsed=time;const key=`${this.engine.r?.id||0}:${this.engine.r?.stage||0}`;if(key!==this.mapKey)this.buildMap();this.battle(!!this.engine.r?.battle);const p=this.engine.position;let dx=this.actions.x,dy=this.actions.y;
  if(!this.actions.blocked&&!this.titleMode&&!this.engine.r?.battle){if(dx||dy){this.path=[];this.targetObject=null;this.marker.setVisible(false);}else if(this.path.length){const t=this.path[0],dist=Math.hypot(t.x-p.x,t.y-p.y);if(dist<.1)this.path.shift();else{dx=t.x-p.x;dy=t.y-p.y;}}this.engine.move(dx,dy,delta/1000);if(dx||dy){const d=Math.abs(dx)>Math.abs(dy)?(dx>0?1:3):(dy>0?0:2);this.hero.play('walk'+d,true);}else this.hero.anims.stop();if(this.targetObject&&Math.hypot(this.targetObject.x-p.x,this.targetObject.y-p.y)<1.45){const o=this.targetObject;this.clearInput();this.engine.interact(o);}if(!this.path.length)this.marker.setVisible(false);}else this.hero.anims.stop();
  this.positionHero();for(const a of this.actorViews){const done=this.engine.objectDone(a.o.id),visible=!done&&(!a.o.secret||Math.hypot(a.o.x-p.x,a.o.y-p.y)<2.2);a.view.setVisible(visible);a.shadow.setVisible(visible);a.label.setVisible(visible);if(this.engine.p.settings.motion&&visible)a.view.y=a.baseY+Math.sin(time/550+a.o.x)*2;}if(this.battleViews&&this.engine.p.settings.motion)this.battleViews.enemy.y=this.battleViews.enemyBaseY+Math.sin(time/450)*3;this.worldLayer.sort('depth');if(this.lastFogX!==Math.round(p.x)||this.lastFogY!==Math.round(p.y)){this.lastFogX=Math.round(p.x);this.lastFogY=Math.round(p.y);this.drawFog();}this.actions.onFrame?.();}
 drawFog(){this.mist.clear();if(!this.engine.r||this.titleMode)return;const m=this.engine.map,p=this.engine.position,seen=new Set(this.engine.r.seen);for(let y=0;y<m.height;y++)for(let x=0;x<m.width;x++){const d=Math.hypot(x-p.x,y-p.y),key=y*m.width+x;if(d<7)seen.add(key);if(d>5){this.mist.fillStyle(0x04141c,seen.has(key)?.35:.76);this.mist.fillRect(x*TILE,y*TILE,TILE,TILE);}}this.engine.r.seen=[...seen];}
}
