window.FIZJO_RPG_CONTENT = (() => {
  const worlds = [
    {id:'physio',name:'Cytadela Ruchu',icon:'⚕',color:'#51d6c3',unlock:0,desc:'Fizjoterapia, testy kliniczne, objawy i rozumowanie kliniczne.',boss:'Strażnik Wzorca',theme:'Kliniczne ruiny i biomechaniczne mechanizmy.'},
    {id:'anatomy',name:'Katakumby Anatomii',icon:'🦴',color:'#ffd166',unlock:1,desc:'Kości, mięśnie, nerwy, płaszczyzny i nazewnictwo.',boss:'Atlas Bez Twarzy',theme:'Kamienne komnaty w kształcie struktur ciała.'},
    {id:'physiology',name:'Miasto Homeostazy',icon:'⚡',color:'#70e38c',unlock:2,desc:'Mięśnie, układ nerwowy, krążenie, oddychanie i energia.',boss:'Entropion',theme:'Żywe laboratorium pulsujące rytmem organizmu.'},
    {id:'psychology',name:'Labirynt Umysłu',icon:'◉',color:'#a98bff',unlock:3,desc:'Uczenie, pamięć, emocje, motywacja i komunikacja.',boss:'Echo Nocebo',theme:'Zmieniający się pałac wspomnień i iluzji.'},
    {id:'medicine',name:'Archiwum Medycyny',icon:'✚',color:'#ff7b8b',unlock:4,desc:'Patologia, czerwone flagi, gojenie i podstawy diagnostyki — bez farmakologii.',boss:'Arbiter Czerwonych Flag',theme:'Biblioteka przypadków i zamkniętych sal diagnostycznych.'},
    {id:'physics',name:'Kuźnia Praw Natury',icon:'Φ',color:'#6eb9ff',unlock:5,desc:'Mechanika, dźwignie, ciśnienie, fale, energia i elektryczność.',boss:'Władca Momentu',theme:'Mechaniczna kuźnia pełna wahadeł, soczewek i pól.'},
    {id:'nature',name:'Dzika Biosfera',icon:'❧',color:'#8fe388',unlock:6,desc:'Ewolucja, ekologia, botanika i adaptacje zwierząt.',boss:'Stary Mycelium',theme:'Żywy las reagujący na decyzje gracza.'},
    {id:'curiosity',name:'Obserwatorium Osobliwości',icon:'✦',color:'#f5a8ff',unlock:7,desc:'Ciekawostki łączące człowieka, naukę, naturę i historię odkryć.',boss:'Kustosz Paradoksów',theme:'Kosmiczne muzeum sekretów i niezwykłych faktów.'}
  ];

  const q = (world,question,answers,correct,explain,term,tag='core') => ({world,question,answers,correct,explain,term,tag});
  const questions = [
    q('anatomy','Która płaszczyzna dzieli ciało na część prawą i lewą?',['Strzałkowa','Czołowa','Poprzeczna','Skośna'],0,'Płaszczyzna strzałkowa przebiega pionowo w kierunku przód–tył; płaszczyzna pośrodkowa dzieli ciało na równe połowy.','Płaszczyzna strzałkowa','terminologia'),
    q('anatomy','Który mięsień jest głównym prostownikiem stawu biodrowego przy dużym obciążeniu?',['Pośladkowy wielki','Pośladkowy średni','Krawiecki','Gruszkowaty'],0,'Mięsień pośladkowy wielki jest silnym prostownikiem biodra, szczególnie w ruchach wymagających dużego momentu siły.','Mięsień pośladkowy wielki','mięśnie'),
    q('anatomy','Nerw pośrodkowy przechodzi przez:',['Kanał nadgarstka','Kanał Guyona','Otwór zasłonowy','Kanał stępu'],0,'Nerw pośrodkowy przebiega przez kanał nadgarstka pod troczkiem zginaczy.','Nerw pośrodkowy','nerwy'),
    q('anatomy','Która kość tworzy panewkę stawu ramiennego?',['Łopatka','Obojczyk','Kość ramienna','Mostek'],0,'Panewka stawu ramiennego jest częścią łopatki.','Panewka stawu ramiennego','kości'),
    q('anatomy','Mięsień piszczelowy przedni odpowiada przede wszystkim za:',['Zgięcie grzbietowe stopy','Zgięcie podeszwowe','Wyprost kolana','Odwodzenie biodra'],0,'Piszczelowy przedni wykonuje zgięcie grzbietowe i wspomaga odwracanie stopy.','Mięsień piszczelowy przedni','mięśnie'),
    q('anatomy','Która struktura łączy mięsień z kością?',['Ścięgno','Więzadło','Łąkotka','Torebka maziowa'],0,'Ścięgno przenosi siłę z mięśnia na kość; więzadło łączy przede wszystkim kość z kością.','Ścięgno','terminologia'),
    q('anatomy','Korzenie nerwu kulszowego pochodzą głównie ze splotu:',['Lędźwiowo-krzyżowego','Szyjnego','Ramiennego','Guzicznego wyłącznie'],0,'Nerw kulszowy powstaje z włókien L4–S3 splotu krzyżowego, będącego częścią kompleksu lędźwiowo-krzyżowego.','Nerw kulszowy','nerwy'),
    q('anatomy','Który mięsień inicjuje odwodzenie ramienia w pierwszych stopniach ruchu?',['Nadgrzebieniowy','Najszerszy grzbietu','Podłopatkowy','Obły większy'],0,'Nadgrzebieniowy inicjuje odwodzenie, a następnie główną rolę przejmuje mięsień naramienny.','Mięsień nadgrzebieniowy','mięśnie'),
    q('anatomy','Łąkotki znajdują się w stawie:',['Kolano','Bark','Biodro','Łokieć'],0,'Łąkotka przyśrodkowa i boczna zwiększają kongruencję powierzchni stawu kolanowego.','Łąkotka','stawy'),
    q('anatomy','Która część kręgosłupa ma fizjologiczną kifozę?',['Piersiowa','Szyjna','Lędźwiowa','Żadna'],0,'Odcinek piersiowy ma kifozę fizjologiczną; szyjny i lędźwiowy — lordozę.','Kifoza piersiowa','kręgosłup'),

    q('physiology','Bezpośrednim źródłem energii dla cyklu mostków aktyna–miozyna jest:',['ATP','Glikogen','Tlen','Kreatyna'],0,'ATP jest bezpośrednio hydrolizowane przez miozynę; inne substraty służą do jego odtwarzania.','ATP','mięsień'),
    q('physiology','Jony wapnia w mięśniu szkieletowym wiążą się głównie z:',['Troponiną C','Miozyną','Kolagenem','Acetylocholiną'],0,'Wapń wiąże troponinę C, przesuwając tropomiozynę i umożliwiając interakcję aktyny z miozyną.','Troponina C','mięsień'),
    q('physiology','Podstawową jednostką kurczliwą mięśnia poprzecznie prążkowanego jest:',['Sarkomer','Akson','Alweola','Osteon'],0,'Sarkomer rozciąga się między liniami Z i zawiera uporządkowane filamenty aktyny oraz miozyny.','Sarkomer','mięsień'),
    q('physiology','Układ współczulny zwykle powoduje:',['Wzrost częstości serca','Spadek czujności','Zwolnienie przewodzenia w sercu','Nasilenie perystaltyki jako reakcję dominującą'],0,'Aktywacja współczulna wspiera reakcję mobilizacyjną, m.in. zwiększając częstość i kurczliwość serca.','Układ współczulny','nerwowy'),
    q('physiology','Gaz przechodzi przez błonę pęcherzykowo-włośniczkową głównie dzięki:',['Dyfuzji','Filtracji aktywnej','Endocytozie','Przewodzeniu nerwowemu'],0,'Tlen i CO₂ przemieszczają się zgodnie z gradientami ciśnień parcjalnych na drodze dyfuzji.','Dyfuzja gazów','oddychanie'),
    q('physiology','Homeostaza oznacza przede wszystkim:',['Dynamiczne utrzymanie względnie stałych warunków wewnętrznych','Brak zmian w organizmie','Stałą temperaturę 37°C w każdych warunkach','Wyłącznie równowagę wodną'],0,'Homeostaza to dynamiczna regulacja wielu zmiennych wokół zakresów optymalnych.','Homeostaza','regulacja'),
    q('physiology','Jednostką funkcjonalną nerki jest:',['Nefron','Neuron','Sarkomer','Osteon'],0,'Nefron filtruje osocze i modyfikuje przesącz poprzez resorpcję oraz sekrecję.','Nefron','narządy'),
    q('physiology','Który układ energetyczny dominuje w pierwszych sekundach bardzo intensywnego wysiłku?',['ATP-PCr','Tlenowy utleniania tłuszczów','Wyłącznie glikoliza tlenowa','Cykl mocznikowy'],0,'System fosfagenowy ATP-PCr bardzo szybko odtwarza ATP przy krótkim, maksymalnym wysiłku.','System ATP-PCr','energia'),
    q('physiology','Potencjał czynnościowy neuronu jest zjawiskiem:',['Wszystko-albo-nic','Stopniowanym bez progu','Mechanicznym','Hormonalnym'],0,'Po przekroczeniu progu klasyczny potencjał czynnościowy ma stereotypową amplitudę.','Potencjał czynnościowy','nerwowy'),
    q('physiology','Wzrost wentylacji podczas wysiłku służy m.in.:',['Dostarczaniu O₂ i usuwaniu CO₂','Produkcji erytrocytów w płucach','Zmniejszaniu przepływu krwi do mięśni','Zatrzymywaniu ciepła'],0,'Wentylacja rośnie wraz z zapotrzebowaniem metabolicznym i pomaga utrzymać równowagę gazową oraz kwasowo-zasadową.','Wentylacja wysiłkowa','oddychanie'),

    q('psychology','Efekt, w którym oczekiwanie negatywnego skutku może nasilać objawy, to:',['Nocebo','Habituacja','Facylitacja','Priming dodatni'],0,'Nocebo opisuje niekorzystne efekty związane z oczekiwaniami i kontekstem, nie wymagające działania farmakologicznego.','Nocebo','oczekiwania'),
    q('psychology','Powtarzanie materiału w rosnących odstępach czasu to:',['Spaced repetition','Flooding','Modelowanie','Maskowanie'],0,'Powtórki rozłożone w czasie poprawiają trwałość pamięci bardziej niż masowe uczenie w jednej sesji.','Spaced repetition','uczenie'),
    q('psychology','Przypominanie odpowiedzi bez podglądania notatek wykorzystuje efekt:',['Retrieval practice','Dysonansu poznawczego','Warunkowania klasycznego','Habituacji'],0,'Aktywne wydobywanie informacji z pamięci wzmacnia późniejszą dostępność wiedzy.','Retrieval practice','uczenie'),
    q('psychology','Motywacja wewnętrzna jest najbardziej związana z:',['Satysfakcją z samej aktywności','Wyłącznie nagrodą pieniężną','Unikaniem każdej trudności','Presją społeczną'],0,'Motywacja wewnętrzna wynika z zainteresowania, autonomii, kompetencji lub satysfakcji z czynności.','Motywacja wewnętrzna','motywacja'),
    q('psychology','Katastrofizacja bólu obejmuje zwykle:',['Ruminacje, wyolbrzymianie i poczucie bezradności','Wyłącznie zaburzenia czucia','Zawsze symulowanie objawów','Tylko brak wiedzy anatomicznej'],0,'Katastrofizacja jest konstruktem poznawczo-emocjonalnym i może wiązać się z większym cierpieniem oraz unikaniem aktywności.','Katastrofizacja','ból'),
    q('psychology','Najlepszy sposób sprawdzenia, czy pacjent zrozumiał instrukcję, to często:',['Poprosić, by wyjaśnił ją własnymi słowami','Powtórzyć ją głośniej','Założyć, że potwierdzenie „tak” wystarczy','Użyć większej liczby terminów technicznych'],0,'Technika teach-back pomaga wykryć nieporozumienia bez obwiniania pacjenta.','Teach-back','komunikacja'),
    q('psychology','Warunkowanie klasyczne polega na:',['Uczeniu związku między bodźcami','Wyłącznie karaniu zachowania','Świadomym zapamiętywaniu list','Uczeniu przez instrukcję tekstową'],0,'W warunkowaniu klasycznym bodziec neutralny może nabrać znaczenia poprzez skojarzenie z bodźcem biologicznie istotnym.','Warunkowanie klasyczne','uczenie'),
    q('psychology','Habituacja to:',['Zmniejszenie reakcji na powtarzający się, niegroźny bodziec','Stały wzrost reakcji na każdy bodziec','Utrata pamięci długotrwałej','Rodzaj urazu nerwu'],0,'Przy habituacji odpowiedź na powtarzający się bodziec może słabnąć, jeśli nie ma on znaczących konsekwencji.','Habituacja','uczenie'),
    q('psychology','Poczucie własnej skuteczności oznacza:',['Przekonanie, że potrafię wykonać potrzebne działanie','Poziom inteligencji','Nastrój w danym dniu','Brak lęku'],0,'Self-efficacy dotyczy wiary w zdolność do wykonania określonego zadania i wpływa na wytrwałość.','Self-efficacy','motywacja'),
    q('psychology','Wzmocnienie pozytywne oznacza:',['Dodanie konsekwencji zwiększającej częstość zachowania','Karanie za błąd','Usunięcie nagrody bez względu na zachowanie','Ignorowanie zachowania'],0,'W terminologii behawioralnej „pozytywne” oznacza dodanie bodźca, a „wzmocnienie” — wzrost prawdopodobieństwa zachowania.','Wzmocnienie pozytywne','uczenie'),

    q('medicine','Nagłe zaburzenie mowy i osłabienie jednej strony ciała wymaga przede wszystkim:',['Pilnej oceny medycznej','Rozciągania szyi','Masażu kończyny','Tygodnia obserwacji'],0,'Nagłe ogniskowe objawy neurologiczne mogą wskazywać na udar i wymagają pilnego działania.','Ogniskowe objawy neurologiczne','red flags'),
    q('medicine','Nowe zaburzenia zwieraczy z drętwieniem w okolicy siodłowej są:',['Czerwoną flagą zespołu ogona końskiego','Typowym objawem DOMS','Zwykłym napięciem pośladków','Objawem wyłącznie mięśniowym'],0,'Zaburzenia zwieraczy i czucia siodłowego wymagają pilnej diagnostyki pod kątem zespołu ogona końskiego.','Zespół ogona końskiego','red flags'),
    q('medicine','Pierwsza faza klasycznego gojenia tkanek po urazie to głównie:',['Hemostaza i zapalenie','Remodeling końcowy','Mineralizacja chrząstki','Hipertrofia mięśni'],0,'Po urazie najpierw ograniczane jest krwawienie i uruchamiana odpowiedź zapalna, później proliferacja i remodeling.','Gojenie tkanek','gojenie'),
    q('medicine','Gorączka, silny ból i szybko szerzące się zaczerwienienie skóry mogą sugerować:',['Proces infekcyjny wymagający oceny medycznej','Wyłącznie DOMS','Zwykłą adaptację treningową','Prawidłową reakcję po każdym masażu'],0,'Objawy ogólne z szybko postępującymi zmianami miejscowymi wymagają ostrożności i diagnostyki.','Infekcja — objawy alarmowe','red flags'),
    q('medicine','MRI najlepiej opisuje przede wszystkim:',['Tkanki miękkie i struktury nerwowe','Wyłącznie stężenie glukozy','Przewodnictwo nerwowe','Ciśnienie tętnicze'],0,'Rezonans magnetyczny zapewnia dobry kontrast tkanek miękkich i nie wykorzystuje promieniowania jonizującego.','MRI','diagnostyka'),
    q('medicine','RTG jest szczególnie użyteczne w ocenie:',['Kości i zmian ich struktury','Aktywności kory mózgu','Stężenia elektrolitów','Czynności mięśni'],0,'Radiografia dobrze uwidacznia struktury kostne, choć interpretacja zależy od wskazania i projekcji.','RTG','diagnostyka'),
    q('medicine','Postępująca, nowa utrata siły mięśniowej jest objawem, który:',['Wymaga pogłębionej oceny neurologicznej','Zawsze jest normalnym zmęczeniem','Powinien być ignorowany przez 6 tygodni','Zawsze mija po rozciąganiu'],0,'Narastający deficyt motoryczny może wskazywać na istotny problem neurologiczny i wymaga odpowiedniej oceny.','Postępujący deficyt siły','red flags'),
    q('medicine','Stan zapalny jest:',['Złożoną odpowiedzią obronną i naprawczą','Zawsze chorobą autoimmunologiczną','Zawsze zakażeniem','Wyłącznie obrzękiem'],0,'Zapalenie obejmuje odpowiedź naczyniową i komórkową; może mieć przyczyny infekcyjne i nieinfekcyjne.','Zapalenie','patologia'),
    q('medicine','Obrzęk jednostronnej łydki z nagłą dusznością wymaga:',['Pilnej oceny medycznej','Wyłącznie automasażu','Rozgrzewki i biegu','Intensywnej kompresji bez oceny'],0,'Taki zestaw objawów może być zgodny z zakrzepicą i zatorowością płucną; wymaga pilnej pomocy.','Zakrzepica / zatorowość — alarm','red flags'),
    q('medicine','Czułość testu diagnostycznego opisuje zdolność do:',['Wykrywania osób z chorobą','Wykluczania wszystkich osób zdrowych','Pomiaru siły mięśniowej','Oceny kosztu badania'],0,'Czułość to odsetek prawdziwie dodatnich wśród osób, które rzeczywiście mają dane schorzenie.','Czułość testu','diagnostyka'),

    q('physics','Moment siły jest iloczynem siły i:',['Ramienia działania siły','Prędkości światła','Gęstości','Czasu reakcji'],0,'Moment siły zależy od wartości siły oraz prostopadłej odległości jej linii działania od osi obrotu.','Moment siły','mechanika'),
    q('physics','Jednostką siły w układzie SI jest:',['Niuton','Dżul','Wat','Pascal'],0,'Niuton (N) to jednostka siły; dżul — energii, wat — mocy, pascal — ciśnienia.','Niuton','jednostki'),
    q('physics','Ciśnienie definiujemy jako:',['Siłę działającą na jednostkę powierzchni','Energię na jednostkę czasu','Masę razy prędkość','Prędkość razy czas'],0,'p = F/A. Ta zależność jest ważna m.in. w biomechanice kontaktu i hydrostatyce.','Ciśnienie','mechanika'),
    q('physics','Praca mechaniczna w najprostszym przypadku to:',['Siła razy przemieszczenie w kierunku siły','Masa razy czas','Ciśnienie razy temperatura','Prędkość podzielona przez drogę'],0,'Dla stałej siły W = F·s·cosθ.','Praca mechaniczna','mechanika'),
    q('physics','Moc opisuje:',['Tempo wykonywania pracy lub przekazywania energii','Całkowitą masę układu','Wyłącznie napięcie elektryczne','Opór ruchu bez czasu'],0,'Moc to praca lub energia przypadająca na jednostkę czasu.','Moc','mechanika'),
    q('physics','Dźwięk w powietrzu jest przede wszystkim falą:',['Mechaniczną podłużną','Elektromagnetyczną','Grawitacyjną','Stojącą w każdych warunkach'],0,'Dźwięk wymaga ośrodka materialnego; w gazach propaguje się głównie jako fala podłużna ciśnienia.','Fala dźwiękowa','fale'),
    q('physics','Prawo Hooke’a w zakresie sprężystym opisuje zależność:',['Siła jest proporcjonalna do odkształcenia','Energia jest proporcjonalna do masy','Ciśnienie nie zależy od powierzchni','Prędkość jest zawsze stała'],0,'W idealnym zakresie sprężystym F = kx. Tkanki biologiczne są bardziej złożone i często nieliniowe.','Prawo Hooke’a','mechanika'),
    q('physics','Dźwignia pierwszego rodzaju ma:',['Oś między siłą a oporem','Opór zawsze między osią a siłą','Siłę zawsze między osią a oporem','Brak osi obrotu'],0,'W dźwigni I rodzaju punkt podparcia leży między siłą a oporem.','Dźwignia I rodzaju','mechanika'),
    q('physics','Jednostką częstotliwości jest:',['Herc','Tesla','Wolt','Lumen'],0,'1 Hz oznacza jeden cykl na sekundę.','Herc','fale'),
    q('physics','Energia kinetyczna rośnie z kwadratem:',['Prędkości','Czasu','Gęstości','Temperatury'],0,'Ek = 1/2 mv², dlatego wzrost prędkości silnie zwiększa energię ruchu.','Energia kinetyczna','mechanika'),

    q('nature','Fotosynteza zachodzi głównie w:',['Chloroplastach','Mitochondriach zwierząt','Jądrze komórkowym','Rybosomach'],0,'Chloroplasty roślin i glonów zawierają aparat fotosyntetyczny, w tym chlorofil.','Chloroplast','botanika'),
    q('nature','Dobór naturalny bezpośrednio faworyzuje cechy, które:',['Zwiększają sukces reprodukcyjny w danych warunkach','Są największe rozmiarowo','Zawsze są nowe','Powstają dlatego, że organizm ich potrzebuje'],0,'Dobór naturalny działa na dziedziczne różnice wpływające na przeżycie i reprodukcję w konkretnym środowisku.','Dobór naturalny','ewolucja'),
    q('nature','Grzyby tworzące mikoryzę współpracują głównie z:',['Korzeniami roślin','Piórami ptaków','Kośćmi ssaków','Muszlami mięczaków'],0,'Mikoryza to symbioza grzybów z korzeniami, poprawiająca m.in. dostęp roślin do wody i części składników mineralnych.','Mikoryza','ekologia'),
    q('nature','Największą część atmosfery Ziemi stanowi:',['Azot','Tlen','Dwutlenek węgla','Argon'],0,'Azot stanowi około 78% suchego powietrza, tlen około 21%.','Atmosfera Ziemi','ziemia'),
    q('nature','Zapylanie to przeniesienie:',['Pyłku na znamię słupka lub odpowiednią strukturę rozrodczą','Nasion do gleby','Wody do korzeni','Cukrów do liści'],0,'Zapylanie poprzedza zapłodnienie u roślin nasiennych.','Zapylanie','botanika'),
    q('nature','Nietoperze orientują się w ciemności m.in. dzięki:',['Echolokacji','Fotosyntezie','Elektrolizie','Polaryzacji kości'],0,'Wiele gatunków emituje ultradźwięki i analizuje ich echo, choć wykorzystuje też wzrok i inne zmysły.','Echolokacja','zoologia'),
    q('nature','Porost jest klasycznie przykładem współżycia:',['Grzyba z partnerem fotosyntetyzującym','Dwóch gatunków ssaków','Bakterii wyłącznie chorobotwórczych','Rośliny z owadem pasożytniczym'],0,'Porosty są złożonymi układami, zwykle grzyba z glonem lub sinicą, a współczesne badania pokazują jeszcze większą złożoność.','Porost','ekologia'),
    q('nature','Bioróżnorodność obejmuje różnorodność:',['Genów, gatunków i ekosystemów','Wyłącznie gatunków zwierząt','Tylko mikroorganizmów','Wyłącznie klimatu'],0,'Pojęcie bioróżnorodności stosuje się na kilku poziomach organizacji biologicznej.','Bioróżnorodność','ekologia'),
    q('nature','Mitochondria komórek eukariotycznych są wiązane ewolucyjnie z:',['Endosymbiozą dawnych bakterii','Powstaniem bez udziału błon','Wyłącznie wirusami','Fotosyntezą jądra komórkowego'],0,'Teoria endosymbiotyczna wyjaśnia m.in. własne DNA i podwójną błonę mitochondriów.','Endosymbioza','ewolucja'),
    q('nature','Główną rolą aparatów szparkowych liścia jest regulacja:',['Wymiany gazowej i utraty wody','Syntezy DNA','Budowy korzenia','Ruchu nasion'],0,'Aparaty szparkowe kontrolują dyfuzję CO₂, O₂ i pary wodnej.','Aparaty szparkowe','botanika'),

    q('curiosity','Który narząd zużywa dużą część energii spoczynkowej mimo niewielkiej masy?',['Mózg','Ścięgno Achillesa','Paznokieć','Łąkotka'],0,'Mózg stanowi niewielki procent masy ciała, ale ma wysokie zapotrzebowanie metaboliczne.','Energetyka mózgu','człowiek'),
    q('curiosity','Dlaczego kości są jednocześnie lekkie i odporne mechanicznie?',['Mają strukturę hierarchiczną i beleczkową dopasowaną do obciążeń','Są pełnymi blokami metalu','Nie ulegają przebudowie','Są zbudowane wyłącznie z kolagenu'],0,'Kość łączy fazę mineralną i organiczną, a architektura korowa i beleczkowa poprawia stosunek wytrzymałości do masy.','Architektura kości','człowiek'),
    q('curiosity','Które zwierzę słynie z regeneracji kończyn i części narządów?',['Aksolotl','Gepard','Sokół','Koala'],0,'Aksolotle są modelowym organizmem badań nad regeneracją kończyn i tkanek.','Aksolotl','natura'),
    q('curiosity','Fenomen, w którym mózg „uzupełnia” brakujące informacje wzrokowe, pokazuje znaczenie:',['Predykcji i interpretacji percepcji','Wyłącznie ostrości siatkówki','Braku pamięci','Siły mięśni oka'],0,'Percepcja jest aktywnym procesem, w którym mózg integruje dane sensoryczne z kontekstem i przewidywaniami.','Percepcja predykcyjna','psychologia'),
    q('curiosity','Dlaczego lód unosi się na wodzie?',['Ma mniejszą gęstość niż ciekła woda','Ma większą masę atomową','Nie podlega grawitacji','Zawsze zawiera powietrze'],0,'Struktura krystaliczna lodu zajmuje większą objętość, przez co jego gęstość jest mniejsza od gęstości ciekłej wody.','Anomalia gęstości wody','fizyka'),
    q('curiosity','Które włókna nerwowe przewodzą zwykle najszybciej?',['Grube, silnie mielinizowane','Cienkie, bezmielinowe','Wszystkie identycznie','Wyłącznie autonomiczne'],0,'Większa średnica i mielinizacja zwiększają szybkość przewodzenia dzięki przewodzeniu skokowemu.','Mielinizacja','fizjologia'),
    q('curiosity','Dlaczego trening siłowy na początku poprawia wyniki także przed dużą hipertrofią?',['Istotną rolę odgrywają adaptacje nerwowe i koordynacyjne','Kość natychmiast podwaja masę','Zmienia się długość kończyn','Mięśnie przestają potrzebować ATP'],0,'Wczesne zyski siły obejmują m.in. lepszą rekrutację i koordynację jednostek motorycznych oraz uczenie ruchu.','Adaptacje nerwowe','trening'),
    q('curiosity','Zjawisko „ślepej plamki” wynika z miejsca, gdzie:',['Nerw wzrokowy opuszcza siatkówkę','Soczewka styka się z rogówką','Źrenica jest największa','Mięśnie oka krzyżują się'],0,'W tarczy nerwu wzrokowego nie ma fotoreceptorów, a mózg zwykle uzupełnia brakującą informację.','Ślepa plamka','neuro'),
    q('curiosity','Który materiał biologiczny ma wyjątkowo wysoką wytrzymałość na rozciąganie względem masy?',['Nić pajęcza','Tkanka tłuszczowa','Szkliwo wyłącznie na ściskanie','Śluz'],0,'Wiele rodzajów jedwabiu pajęczego łączy wysoką wytrzymałość i dużą zdolność pochłaniania energii.','Jedwab pajęczy','natura'),
    q('curiosity','Czemu czerwone krwinki ssaków nie mają jądra?',['Zwiększa to miejsce na hemoglobinę i elastyczność komórki','Nie są komórkami','Jądro rozpuszcza tlen','Powstają bez DNA'],0,'Dojrzałe erytrocyty ssaków tracą jądro w toku dojrzewania, co wspiera ich wyspecjalizowaną funkcję transportową.','Erytrocyt','fizjologia')
  ];

  const glossary = [
    ['Proksymalny','Położony bliżej początku kończyny lub punktu przyczepu.','anatomy'],['Dystalny','Położony dalej od początku kończyny lub punktu przyczepu.','anatomy'],['Ipsilateralny','Znajdujący się po tej samej stronie ciała.','anatomy'],['Kontralateralny','Znajdujący się po przeciwnej stronie ciała.','anatomy'],
    ['Aferentny','Przewodzący informację w kierunku ośrodkowego układu nerwowego.','physiology'],['Eferentny','Przewodzący sygnały od ośrodkowego układu nerwowego do efektorów.','physiology'],['Nocycepcja','Neuronalny proces kodowania bodźców potencjalnie zagrażających tkankom; nie jest synonimem bólu.','physiology'],
    ['Sensytyzacja','Wzrost reaktywności układu na bodźce; może dotyczyć mechanizmów obwodowych lub ośrodkowych.','physio'],['Dermatom','Obszar skóry związany głównie z aferentacją jednego korzenia rdzeniowego.','physio'],['Miotom','Grupa mięśni/zakres ruchu związany funkcjonalnie z segmentem nerwowym.','physio'],
    ['Placebo','Korzystny efekt zależny od kontekstu, oczekiwań i uczenia, nie tylko od specyficznego działania interwencji.','psychology'],['Nocebo','Niekorzystny efekt związany z oczekiwaniami i kontekstem.','psychology'],['Samouskutecznienie','Przekonanie o własnej zdolności do wykonania określonego działania.','psychology'],
    ['Czułość','Odsetek wyników dodatnich wśród osób rzeczywiście posiadających daną cechę/chorobę.','medicine'],['Swoistość','Odsetek wyników ujemnych wśród osób bez danej cechy/choroby.','medicine'],['Red flag','Objaw lub kontekst zwiększający podejrzenie poważnej patologii i potrzebę odpowiedniej oceny.','medicine'],
    ['Moment siły','Tendencja siły do wywołania obrotu wokół osi.','physics'],['Impedancja','Miara przeciwstawiania się układu przepływowi energii; znaczenie zależy od rodzaju układu.','physics'],['Częstotliwość','Liczba cykli zjawiska okresowego na jednostkę czasu.','physics'],
    ['Nisza ekologiczna','Zespół wymagań, zasobów i relacji określających funkcjonowanie gatunku w ekosystemie.','nature'],['Homeostaza','Dynamiczne utrzymywanie parametrów środowiska wewnętrznego w odpowiednim zakresie.','physiology']
  ].map(([term,definition,world],i)=>({id:'g'+i,term,definition,world}));

  const skillTrees = {
    physio:[['Diagnostyka funkcjonalna','Więcej Knowledge XP za pytania kliniczne'],['Testy specjalne','Zwiększa obrażenia Insight podczas walk klinicznych'],['Programowanie ruchu','Lepsza jakość lootów po questach ruchowych'],['Rozumowanie kliniczne','Szansa na ujawnienie słabości bossa'],['Bezpieczeństwo','Pierwszy błędny wybór red flag nie zrywa combo'],['Mistrz gabinetu','Odblokowuje elitarną salę Cytadeli']],
    anatomy:[['Osteologia','Bonus za pytania o kości'],['Miologia','Bonus za mięśnie i przyczepy'],['Neuroanatomia','Bonus za nerwy i korzenie'],['Artrologia','Bonus za stawy'],['Topografia','Więcej sekretów na mapie'],['Atlas żywy','Odkrywa zaawansowany kodeks anatomii']],
    physiology:[['Mięsień','Wzmocnienie skilli wysiłkowych'],['Neurofizjologia','Szybsze ładowanie Insight'],['Krążenie','Więcej HP po odpoczynku'],['Oddychanie','Regeneracja między starciami'],['Energetyka','Więcej akcji specjalnych'],['Homeostaza','Premia do wszystkich zasobów w długim runie']],
    psychology:[['Pamięć','Wyższy mnożnik za serie poprawnych odpowiedzi'],['Motywacja','Bonus do dziennego streaku'],['Ból i percepcja','Ujawnia pułapki poznawcze przeciwników'],['Komunikacja','Lepsze nagrody z NPC'],['Uczenie','Szybsze odblokowywanie fiszek'],['Metapoznanie','Podpowiedź do jednego pytania na run']],
    medicine:[['Red flags','Wykrywa niebezpieczne zdarzenia'],['Patologia','Bonus do bossów klinicznych'],['Gojenie','Lepsze leczenie między pokojami'],['Diagnostyka obrazowa','Ujawnia część mapy'],['Epidemiologia','Lepsza ocena ryzyka'],['Triaging','Odblokowuje Archiwum Przypadków']],
    physics:[['Mechanika','Silniejsze ataki fizyczne'],['Fale','Bonus do efektów dźwiękowych/energii'],['Dźwignie','Krytyki przy dobrym pozycjonowaniu'],['Energia','Większy maksymalny Insight'],['Ciśnienie','Lepsza obrona'],['Biomechanika','Łączy bonusy fizyki i fizjo']],
    nature:[['Botanika','Znajdujesz więcej materiałów'],['Zoologia','Bonus do bestiariusza'],['Ekologia','Lepsze nagrody za eksplorację'],['Ewolucja','Adaptacyjne bonusy po porażce'],['Mikologia','Sekretne receptury craftingu'],['Biosfera','Odblokowuje legendarny biom']],
    curiosity:[['Łącznik','Bonus za pytania interdyscyplinarne'],['Paradoksy','Więcej sekretów'],['Historia odkryć','Bonus do artefaktów'],['Obserwacja','Ujawnia ukryte przejścia'],['Eksperyment','Losowy buff za poprawną odpowiedź'],['Polimat','Globalny bonus do Knowledge XP']]
  };

  const enemies = {
    physio:[['Kompensator',18,4],['Strażnik Sztywności',22,5],['Widmo Bólu',20,6],['Fałszywy Wzorzec',24,5]],
    anatomy:[['Osteoklast Cienia',22,5],['Nerwobłąd',20,7],['Strażnik Powięzi',26,5],['Łąkotnik',24,6]],
    physiology:[['Deficyt ATP',24,7],['Szum Synaptyczny',22,7],['Dyshomeostaza',28,6],['Hipowentyl',25,7]],
    psychology:[['Ruminator',24,7],['Katastrofizer',27,7],['Noceboid',25,8],['Dysonans',29,6]],
    medicine:[['Czerwona Flaga',30,8],['Maskowany Objaw',28,8],['Fałszywie Ujemny',27,9],['Chaos Diagnostyczny',32,7]],
    physics:[['Tarciowiec',28,8],['Momentor',30,9],['Rezonans',26,10],['Entropik',33,8]],
    nature:[['Pasożyt Cienia',30,9],['Inwazyjny',32,9],['Suchorost',28,10],['Mutant Losowy',35,8]],
    curiosity:[['Paradoks',32,10],['Anomalia',35,9],['Kustosz Fałszu',36,10],['Szum Informacyjny',34,11]]
  };

  const itemNames = {
    weapon:['Skalpel Logiki','Młot Biomechanika','Kostur Synapsy','Rapier Pytania','Topór Atlasu','Laska Homeostazy'],
    armor:['Płaszcz Powięzi','Zbroja Korowa','Kamizela Homeostazy','Pancerz Krytycznego Myślenia','Płaszcz Mycelium'],
    charm:['Amulet Dermatomu','Pierścień Retrievalu','Soczewka Diagnosty','Kompas Dźwigni','Totem Mikoryzy','Moneta Paradoksu']
  };

  return {worlds,questions,glossary,skillTrees,enemies,itemNames};
})();
